var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,aa,Y){f!=Array.prototype&&f!=Object.prototype&&(f[aa]=Y.value)};$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var f=0;return function(aa){return $jscomp.SYMBOL_PREFIX+(aa||"")+f++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.iterator;f||(f=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[f]&&$jscomp.defineProperty(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(f){var aa=0;return $jscomp.iteratorPrototype(function(){return aa<f.length?{done:!1,value:f[aa++]}:{done:!0}})};$jscomp.iteratorPrototype=function(f){$jscomp.initSymbolIterator();f={next:f};f[$jscomp.global.Symbol.iterator]=function(){return this};return f};
$jscomp.iteratorFromArray=function(f,aa){$jscomp.initSymbolIterator();f instanceof String&&(f+="");var Y=0,H={next:function(){if(Y<f.length){var wb=Y++;return{value:aa(wb,f[wb]),done:!1}}H.next=function(){return{done:!0,value:void 0}};return H.next()}};H[Symbol.iterator]=function(){return H};return H};
$jscomp.polyfill=function(f,aa,Y,H){if(aa){Y=$jscomp.global;f=f.split(".");for(H=0;H<f.length-1;H++){var wb=f[H];wb in Y||(Y[wb]={});Y=Y[wb]}f=f[f.length-1];H=Y[f];aa=aa(H);aa!=H&&null!=aa&&$jscomp.defineProperty(Y,f,{configurable:!0,writable:!0,value:aa})}};
$jscomp.polyfill("Array.prototype.fill",function(f){return f?f:function(f,Y,H){var aa=this.length||0;0>Y&&(Y=Math.max(0,aa+Y));if(null==H||H>aa)H=aa;H=Number(H);0>H&&(H=Math.max(0,aa+H));for(Y=Number(Y||0);Y<H;Y++)this[Y]=f;return this}},"es6","es3");
function PEvs(f,aa,Y,H,wb,Vf,Oe){var Ia,fc,Sa,td,gc,da,xb,xc,Yc,Pe,cb,yc=0,zc=0,Zc,Ja=!1,yb=!1,lb=0,db=0,hc=0,ic=0,R=function(p){xb=p.target;for(Yc=xc=0;xb;)xc+=xb.offsetLeft-xb.scrollLeft,Yc+=xb.offsetTop-xb.scrollTop,xb=xb.offsetParent;yc=p.pageX-xc-document.body.scrollLeft;zc=p.pageY-Yc-document.body.scrollTop};this.getX=function(){return yc};this.getY=function(){return zc};var Ka=function(p){p.preventDefault();p.stopImmediatePropagation?p.stopImmediatePropagation():p.stopPropagation()},I=function(p){R(p);
Zc=yc;qa=zc;ua=!0;null!=ud&&(td=(new Date).getTime());null!=Lb&&Lb(p)},eb=function(p){ua&&(R(p),ua=!1,null!=zb&&zb(p),null!=ud&&(gc=(new Date).getTime(),da=gc-td,300>da&&ud(p)))},vd=function(p){R(p);3>Math.abs(yc-Zc)&&3>Math.abs(zc-qa)||(qa=Zc=-9999,ua?null!=S&&S(p):null!=La&&La(p),null!=ea&&va())};this.touchDown=function(p){Sa=!0;if(1<p.targetTouches.length)return Ja=!0,cb&&(db=-1,Ka(p)),!1;Ia=p.changedTouches;fc=Ia[0];I(fc)};this.touchUp=function(p){0==p.targetTouches.length&&(Ja=Sa=!1);Ka(p);if(Ja||
yb)return Ja||(yb=!1),!1;Ia=p.changedTouches;fc=Ia[0];eb(fc)};this.touchMove=function(p){Sa=!0;Ka(p);if(Ja)return cb&&(Ia=p.targetTouches,yb=!0,hc=Ia[0].pageX-Ia[1].pageX,ic=Ia[0].pageY-Ia[1].pageY,lb=hc*hc+ic*ic,cb&&0<db&&0!=lb-db&&cb(0<lb-db?1:-1),db=lb),!1;Ia=p.changedTouches;fc=Ia[0];vd(fc)};this.pointUp=function(p){Ka(p);for(var f=0;f<J.length;f++)if(J[f].pointerId==p.pointerId){J.splice(f,1);break}0==J.length&&(Sa=Ja=!1);if(Ja||yb)return Ja||(yb=!1),!1;eb(p);return!1};this.pointDown=function(p){Ka(p);
J.push(p);db=-1;Sa=!0;1<J.length?Ja=!0:I(p);return!1};this.pointMove=function(p){Ka(p);for(var f=0;f<J.length;f++)J[f].pointerId==p.pointerId&&(J[f]=p);if(Ja||!yb){if(Ja)return cb&&(yb=!0,hc=J[0].pageX-J[1].pageX,ic=J[0].pageY-J[1].pageY,lb=hc*hc+ic*ic,cb&&0<db&&3<Math.abs(lb-db)&&cb(0<lb-db?1:-1),db=lb),!1;vd(p);return!1}};this.mouseDown=function(f){Sa||(Ka(f),I(f))};this.clearDown=function(){ua=!1};this.mouseUp=function(f){Sa||(Ka(f),eb(f))};this.useWheel=function(p){f.addEventListener("wheel",
this.mouseWheel,!0);cb=p};this.mouseWheel=function(f){R(f);var p=Math.max(-1,Math.min(1,-f.deltaY||-f.detail));Ka(f);cb&&cb(p)};this.mouseClick=function(f){Ka(f);ua=!1};this.mouseMove=function(f){Sa||(Ka(f),vd(f))};this.mouseDragged=function(f){Sa||(Ka(f),R(f),null!=S&&S(f),null!=ea&&va())};var va=function(){clearTimeout(Pe);Pe=setTimeout(function(){ea()},600)};var qa=Zc=zc=yc=0;var Lb=aa;var zb=Y;var La=H;var S=wb;var ud=Vf;var ea=Oe;var ua=Sa=!1;var J=[];f.addEventListener("mousedown",this.mouseDown,
!1);f.addEventListener("mouseup",this.mouseUp,!1);f.addEventListener("mousemove",this.mouseMove,!1);f.addEventListener("click",this.mouseClick,!1);window.PointerEvent?(f.addEventListener("pointerdown",this.pointDown,!1),f.addEventListener("pointerup",this.pointUp,!1),f.addEventListener("pointermove",this.pointMove,!1),f.addEventListener("pointerleave",this.pointUp,!1),f.addEventListener("pointercancel",this.pointUp,!1)):(f.addEventListener("touchstart",this.touchDown,!1),f.addEventListener("touchend",
this.touchUp,!1),f.addEventListener("touchmove",this.touchMove,!1),f.addEventListener("touchleave",this.touchUp,!1),f.addEventListener("touchcancel",this.touchUp,!1));f.addEventListener("contextmenu",function(f){f.preventDefault()},!1);f.style["touch-action"]="none";f.addEventListener("mouseout",function(f){ua||(zc=yc=-1,null!=La&&La(f));ua=!1})};var HAniS=new function(){function f(b){var a,d;$c=!0;if(b instanceof Array)for(e={},a=0;a<b.length;a++){if(!(2>b[a].length)){var c=b[a].trim();if(0!=c.indexOf("#")){var n=c.indexOf("=");if(!(1>n)){var q=c.substr(0,n).trim().toLowerCase();e[q]=c.substr(n+1).trim()}}}}else e=b;de=!1;a=e.debug;null!=a&&("true"==a?(Qe=window.open("","HAniSDebugInfo","scrollbars=yes,width=400,height=200"),de=!0,J("HAniS Version 4.22")):de=!1);fb=!0;a=e.set_className;null!=a&&B(a,"f")&&(fb=!1);J("Is type of param an array = "+
(b instanceof Array));a=e.divalign;null!=a&&(wd=a.trim(),z.align=wd);a=e.prevent_shortcuts;null!=a&&B(a,"t")&&(ee=!0);a=e.initial_message;null!=a&&(b=e.initial_message_style,null==b&&(b="background-color:red;top:10px;left:10px;height:100px;width:200px"),b="z-index:99;position:absolute;"+b,jc=t("div"),jc.setAttribute("style",b),jc.innerHTML=a,jc.addEventListener("click",function(){jc.style.visibility="hidden"},!1),jc.style.visibility="visible",Ta.appendChild(jc),b=e.initial_message_timeout,null!=b&&
("auto"==b?Re=!0:(Re=!1,b=parseInt(e.initial_message_timeout,10),2>b&&(b=2),setTimeout(function(){jc.style.visibility="hidden"},1E3*b))));a=e.coordinates;null!=a&&wb(a);c="green";n="white";q="12px Arial";var k=null,h=d=10,f=10;Se=2;Wf="Lat = ";Xf=" Lon = ";a=e.coordinates_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),n=b[1].trim(),q=b[2].trim(),3<b.length&&(Wf=b[3],Xf=b[4],Se=parseInt(b[5],10),6<b.length&&(k=b[6].trim(),d=parseInt(b[7],10),h=parseInt(b[8],10),f=parseInt(b[9],10))));Yf=new zb(c,
n,q,k,d,h,f);fe=Ac=null;null!=e.map_scale&&(ge=kc=!0,b=e.map_scale.split(","),Ac=parseFloat(b[0]),fe=1<b.length?parseFloat(b[1]):Ac);Zf=" ";a=e.distance_unit;null!=a&&(Zf=a.trim());a=e.divcan_style;null!=a&&a.trim();Te="default";a=e.distance_cursor;null!=a&&(Te=a.trim());he="default";a=e.location_cursor;null!=a&&(he=a.trim());ie="default";a=e.probe_cursor;null!=a&&(ie=a.trim());Ue="default";a=e.mark_cursor;null!=a&&(Ue=a.trim());a=e.imagecan_style;null!=a&&(b=a.trim()+";position:absolute;top:0;left:0;",
Ab.setAttribute("style",b+"z-index:1;"),lc.setAttribute("style",b+"z-index:6;"));c="blue";n="white";q="12px Arial";k=null;f=h=d=10;$f=1;ag="white";a=e.distance_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),n=b[1].trim(),ag=5<=b.length?b[4].trim():n,q=b[2].trim(),$f=parseInt(b[3],10),5<b.length&&(k=b[5].trim(),d=parseInt(b[6],10),h=parseInt(b[7],10),f=parseInt(b[8],10)));zh=new zb(c,n,q,k,d,h,f);c="black";n="white";q="12px Arial";k=null;f=h=d=10;a=e.probe_display_style;null!=a&&(b=a.split(","),
c=b[0].trim(),n=b[1].trim(),q=b[2].trim(),3<b.length&&(k=b[3].trim(),d=parseInt(b[4],10),h=parseInt(b[5],10),f=parseInt(b[6],10)));Ah=new zb(c,n,q,k,d,h,f);bg="Undefined";cg=!1;xd=0;a=e.probe_undefined;null!=a&&(b=a.split(","),bg=b[0].trim(),1<b.length&&(xd=parseInt(b[1],10)+1),2<b.length&&(cg=!0));Ve=!1;e.probe_base_image&&(Ve=!0);a=e.active_probe;null!=a&&(Mb=!0);a=e.pause;null!=a&&(dg=parseInt(a,10));a=e.auto_refresh;null!=a&&(We=6E4*parseInt(a,10),Bc=setInterval("HAniS.reloadFOF();",We),yd=!0);
zd=!1;a=e.enable_smoothing;null!=a&&B(a,"t")&&(zd=!0);je=!0;a=e.check_image_size;null!=a&&B(a,"f")&&(je=!1);eg=!1;a=e.sprites;if(null!=a){b=a.split(",");Xe=new Image;Ye=[];Ze=[];Nb=[];Ob=[];if("row"==b[1].trim().toLowerCase())for(h=n=c=0,a=2;a<b.length;)for("row"==b[a].trim().toLowerCase()&&(c=0,n+=h,h=0,a+=1),d=parseInt(b[a],10),a+=1,q=parseInt(b[a],10),a+=1,k=parseInt(b[a],10),k>h&&(h=k),a+=1,f=0;f<d;f++)Ye.push(c),Ze.push(n),Nb.push(q),Ob.push(k),c+=q;else for(n=!1,a=1;a<b.length;)Ye.push(parseInt(b[a],
10)),a+=1,Ze.push(parseInt(b[a],10)),a+=1,a>=b.length?(c=0,n=!0):c=parseInt(b[a],10),0>c?(n=!0,Nb.push(Math.abs(c)),a+=1,c=parseInt(b[a++],10),Ob.push(Math.abs(c))):n?(Nb.push(Nb[Nb.length-1]),Ob.push(Ob[Ob.length-1])):(Nb.push(parseInt(b[a],10)),a+=1,Ob.push(parseInt(b[a],10)),a+=1);Xe.onload=function(){eg=!0};Xe.src=b[0]}a=e.overlay_labels;null!=a&&(Pb=a.split(","));$e=null;a=e.auto_enhance_background;null!=a&&($e=parseInt(a,10)-1);Cc=null;a=e.auto_enhance;if(null!=a)for(c=e.overlay_probe_table,
b=a.split(","),Cc=Array(b.length),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?Cc[a]=-1:Cc[a]=parseInt(b[a].trim(),10)-1,null==c&&(mc[a]=Cc[a]);Dc=!1;mb=-1;a=e.overlay_enhance;null!=a&&(Dc=!0,mb=parseInt(a,10)-1);nc=null;ad=!0;a=e.overlay_allow_hoverzones;if(null!=a)for(b=a.split(","),nc=Array(b.length),a=0;a<b.length;a++)if(nc[a]=!0,B(b[a],"n")||B(b[a],"f"))nc[a]=!1;T=X=null;af=fg=!1;a=e.window_size;null!=a&&(b=a.split(","),"div"==b[0]?af=!0:(T=parseInt(b[0],10),X=parseInt(b[1],10)),fg=!0);
Ad=[];a=e.use_for_all_frames;if(null!=a)for(b=a.split(","),a=0;a<b.length;a+=2)Ad[parseInt(b[a],10)]=parseInt(b[a+1],10)-1;Bd=-1;a=e.skip_missing;null!=a&&(Bd=parseInt(a,10));gg="#00000000";a=e.skip_missing_color;null!=a&&(gg=a);ke=null;a=e.overlay_spacer;if(null!=a)for(b=a.split(","),ke=Array(b.length),a=0;a<b.length;a++)ke[a]=parseInt(b[a],10);a=e.overlay_probe_table;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?mc[a]=-1:mc[a]=parseInt(b[a],10)-1;bf=[];a=e.overlay_ontop;
if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)bf[parseInt(b[a],10)-1]=!0;Ec=null;a=e.overlay_order;null==a&&(a=e.overlay_zorder);if(null!=a)for(b=a.split(","),Ec=Array(b.length),a=0;a<b.length;a++)Ec[parseInt(b[a],10)-1]=a;Qb=null;a=e.overlay_links;if(null!=a)for(b=a.split(","),Qb=Array(b.length),a=0;a<b.length;a++)Qb[a]=parseInt(b[a],10);hg=[];K=null;a=e.overlay_slice;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)hg[parseInt(b[a],10)-1]=!0;ig=!0;a=e.slice_smoothing;B(a,"f")&&(ig=!1);bd=null;
a=e.overlay_clear;if(null!=a)for(b=a.split(","),bd=Array(b.length),a=0;a<b.length;a++)bd[a]=b[a].trim().toLowerCase();jg=!1;a=e.transparency;null!=a&&(b=a.split(","),1==b.length?kg=lg=mg=parseInt(b[0],10):(kg=parseInt(b[0],10),lg=parseInt(b[1],10),mg=parseInt(b[2],10)),jg=!0);cf=!1;a=e.transparency_list;if(null!=a){b=a.split(",");ng=[];for(a=0;a<b.length;a++)ng[parseInt(b[a].trim(),10)-1]=!0;cf=!0}le=null;a=e.overlay_transparent_amount;if(null!=a)for(b=a.split(","),le=Array(b.length),a=0;a<b.length;a++)le[a]=
parseFloat(b[a])/100;Fc=null;a=e.overlay_zoom;if(null!=Pb&&null!=a)for(b=a.split(","),Fc=Array(b.length),a=0;a<b.length;a++)if(Fc[a]=1,B(b[a],"n")||B(b[a],"f"))Fc[a]=0;else if(B(b[a],"d")||B(b[a],"h"))Fc[a]=-1;nb=null;og=[];a=e.overlay_preserve_list;if(null!=Pb&&null!=a)for(b=a.split(","),nb=Array(b.length),a=0;a<b.length;a++){nb[a]=!0;if(B(b[a],"n")||B(b[a],"f"))nb[a]=!1;if(B(b[a],"a")||B(b[a],"A"))og[a]=!0}Z=null;if(null!=Pb&&null!=nb)for(b=e.overlay_preserve.replace(/&/g,",&,").split(","),c=e.overlay_preserve_position,
null!=c&&(c=c.split(",")),n=0,Z=Array(nb.length),a=q=0;a<nb.length;a++)if(nb[a]){Z[a]=[];k=0;do{Z[a][k]=[];for(d=0;4>d;d++)Z[a][k][d]=parseInt(b[q].trim(),10),q+=1;Z[a][k][2]=Z[a][k][2]-Z[a][k][0]+1;Z[a][k][3]=Z[a][k][3]-Z[a][k][1]+1;null!=c?(Z[a][k][4]=parseInt(c[n],10),Z[a][k][5]=parseInt(c[n+1],10),n+=2):(Z[a][k][4]=Z[a][k][0],Z[a][k][5]=Z[a][k][1]);q<b.length&&"&"==b[q].trim()?(q+=1,k+=1,d=!0):d=!1}while(d)}me=0;pg=" ";oc="white";Cd="transparent";Dd="14pt arial";qg=!1;a=e.times_label_style;null!=
a&&(b=a.split(","),oc=b[0].trim(),1<b.length&&(me=Math.floor(60*parseFloat(b[1]))),1<b.length&&(me="?"==b[1].trim()||"auto"==b[1].trim().toLowerCase()?-Math.floor((new Date).getTimezoneOffset()):Math.floor(60*parseFloat(b[1]))),2<b.length&&(pg=b[2].trim()),3<b.length&&(Cd=b[3].trim()),4<b.length&&(Dd=b[4].trim()),5<b.length&&-1!=b[5].trim().indexOf("t")&&(qg=!0));0==oc.indexOf("0x")&&(oc="#"+oc.substring(2));0==Cd.indexOf("0x")&&(Cd="#"+Cd.substring(2));cd=parseInt(Dd,10);Bh=new zb("black","white",
Dd,"black",20,5,5);rg=!1;a=e.to_from_lock;null!=a&&(rg=B(a,"t")?!0:!1);a="black";d="white";h="14px arial";c=null;k=q=n=10;sg=tg=" ";df=dd=null;a=e.dirspd_display_style;null!=a&&(b=a.split(","),a=b[0].trim(),d=b[1].trim(),h=b[2].trim(),sg=b[3],tg=b[4],5<b.length&&(c=b[5].trim(),n=parseInt(b[6],10),q=parseInt(b[7],10),k=parseInt(b[8],10)),df=new zb(a,d,h,c,n,q,k));c="black";n="white";q="14px arial";k=null;f=h=d=10;a=e.tipbox_display_style;null!=a&&(b=a.split(","),c=b[0].trim(),n=b[1].trim(),q=b[2].trim(),
3<b.length&&(k=b[3].trim(),d=parseInt(b[4],10),h=parseInt(b[5],10),f=parseInt(b[6],10)));ug=new zb(c,n,q,k,d,h,f);ne=null;ba=e.image_base;null!=ba?ne=ba=ba.trim():ba=null!=e.image_only_base?e.image_only_base.trim():null;vg=ba;a=e.overlay_base;null!=a&&(pc=a.trim());$c=!0;a=e.filenames;null==a&&(a=e.background_filenames);null!=a&&Ch(a);a=e.basename;null!=a&&(c=e.base_starting_number,n=0,q=1,null!=c&&(b=c.split(","),n=parseInt(b[0],10),1<b.length&&(q=parseInt(b[1],10))),y=e.num_frames,null==y&&(y=e.num_images),
y=parseInt(y,10),Dh(a,n,q));ef=!0;b=e.background_static;null!=b&&(B(b,"f")||B(b,"n"))&&(ef=!1);a=e.overlay_filenames;null!=a&&Eh(a);Ba=null;a=e.image_preserve;if(null!=a)for(b=a.split(","),Ba=[],a=0;a<b.length;a++)Ba[a]=parseInt(b[a].trim(),10),1<a%4&&(Ba[a]=Ba[a]-Ba[a-2]+1);wg=!0;a=e.keep_zoom;null!=a&&B(a,"f")&&(wg=!1);Ed=xg=0;yg=!1;a=e.hide_bottom;null!=a&&(b=a.split(","),xg=parseInt(b[0].trim(),10),1<b.length&&B(b[1],"t")&&(yg=!0));Fd=zg=0;Ag=!1;a=e.hide_top;null!=a&&(b=a.split(","),zg=parseInt(b[0].trim(),
10),1<b.length&&B(b[1],"t")&&(Ag=!0));Gd=Bg=0;Cg=!1;a=e.hide_left;null!=a&&(b=a.split(","),Bg=parseInt(b[0].trim(),10),1<b.length&&B(b[1],"t")&&(Cg=!0));Hd=Dg=0;Eg=!1;a=e.hide_right;null!=a&&(b=a.split(","),Dg=parseInt(b[0].trim(),10),1<b.length&&B(b[1],"t")&&(Eg=!0));Fg=!1;a=e.hide_background;null!=a&&B(a,"t")&&(Fg=!0);Gg="<div>";Hg=300;Ig=500;a=e.popup_style;null!=a&&(Gg='<div style="'+a+'">');a=e.popup_window_size;null!=a&&(b=a.split(","),Ig=b[0],Hg=b[1]);Jg=ta=!1;a=e.active_zoom;null!=a&&B(a,
"t")&&(null==wa&&(ta=!0),ra.useWheel(HAniS.wheel));ff=!1;a=e.cycle_zoom;null!=a&&B(a,"t")&&(ff=!0);a=e.initial_zoom;null!=a&&(b=a.split(","),qc="auto"!=b[0].toLowerCase()?parseFloat(b[0]):"auto",1<b.length?(Id=parseInt(b[1],10),Kg=parseInt(b[2],10)):Id=-1,Lg=!0);ed=1;fd=!1;ja=null;a=e.zoom_scale;if(null!=a)if(b=a.split(","),1===b.length)B(a,"hi_res")?(fd=!0,ed=0):ed=parseFloat(a);else{ja=Array(b.length);for(a=0;a<b.length;a++)ja[a]=parseFloat(b[a]);fd=!0}Gc=9999999;a=e.maximum_zoom;null!=a&&(Gc=parseFloat(a));
gf=!0;a=e.use_progress_bar;null!=a&&B(a,"f")&&(gf=!1);a=e.dwell;null!=a&&(b=a.split(","),gb=parseInt(b[0].trim(),10),1<b.length&&(Rb=parseInt(b[1].trim(),10),10>Rb&&(Rb=10),Hc=parseInt(b[2].trim(),10),hf=parseInt(b[3].trim(),10)));a=e.rate;null!=a&&(b=a.split(","),gb=Math.round(1E4/parseFloat(b[0].trim())),1<b.length&&(Rb=Math.round(1E4/parseFloat(b[2].trim())),10>Rb&&(Rb=10),Hc=Math.round(1E4/parseFloat(b[1].trim()))));a=e.frame_times_template;null!=a&&(b=a.split(","));ob=null;a=e.times;if(null!=
a){b=a.split(",");ob=Array(b.length);for(a=0;a<b.length;a++)ob[a]=parseInt(b[a].trim(),10);Ia(ob)}a=e.extrap_times_filename;if(null!=a){ob=[];var g=new XMLHttpRequest;g.open("get",a,!0);g.onload=function(){for(var a=g.responseText.split("\n"),b=0;b<a.length;b++){var c=a[b].split(" ");if(3==c.length){c[2].trim();var d=parseInt(c[0],10)-1;ob[d]=100*parseInt(c[2].substring(0,2),10)+parseInt(c[2].substring(3,5),10)+parseInt(c[2].substring(6,8),10)/30}}Ia(ob)};g.send()}Jd=null;a=e.extrap_times_template;
null!=a&&(Jd=RegExp(a));Mg=["Click on target's initial position","Click on target's final position","Move pointer around or click here to select target"];Ng=10;a=e.extrap_prompts_position;null!=a&&B(a,"bot")&&(Ng=9999);a=e.extrap_prompts;null!=a&&(Mg=a.split(","));oe=["Click on first point to mark","Save points","Remove last point"];a=e.mark_prompts;null!=a&&(oe=a.split(","));pe=!0;a=e.mark_close;null!=a&&B(a,"f")&&(pe=!1);jf="12pt Arial";Og="white";a=e.mark_prompts_style;null!=a&&(b=a.split(","),
jf=b[0].trim(),1<b.length&&(Og=b[1].trim()));Pg=e.controls;J("controls = "+e.controls);J("bottom_controls = "+e.bottom_controls);Ic=qe=Sb=Tb=pb=qb=Bb=null;null!=Pg&&xb(Pg,!0);Qg=e.bottom_controls;null!=Qg&&xb(Qg,!1);Jc=!1;a=e.probe_table;null!=a&&H(a);b=e.enhance_filename;null==b&&(b=e.enhance_table);if(null!=b){J("Reading enhancement table...");Jc=!1;g=new XMLHttpRequest;rb=[];Kc=[];re=[];Lc=[];Ub=[];var Rg,Ca,v;Ua=[];Va=[];Wa=[];Kd=[];w=-1;Sg=!0;var u=!1,r,p,x,kf,C,m,D,lf,A,F,E,I,G;g.onload=function(){for(var a=
this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var c=a[b].replace(/\s+/g," ").trim(),d=c.indexOf("#");if(0!=d)if(0<d&&(c=c.substring(0,d)),d=c.split(","),0==d[0].indexOf("*"))w++,rb[w]=Array(256),Lc[w]=Array(256),Kc[w]=Array(256),Ub[w]=Array(256),Ua[w]=Array(256),Va[w]=Array(256),Wa[w]=Array(256),Kd[w]=Array(256),rb[w]=Array(256),re[w]=1<d.length?d[1].trim():"None",Rg=" ",Ca="Value =",v=1,c=t("option"),c.innerHTML=d[0].substring(1),c.value=w,null!=xa&&xa.add(c);else{var n=c.indexOf("value");
0>n&&(n=c.indexOf("probe"));u=!1;F=E=0;0<n&&(d=c.substring(n+1),c=c.substring(0,n),n=d.indexOf("="),d=d.substring(n+1),d=d.split(","),1==d.length?(Ca=d[0].trim(),v=-1,u=!1):(F=parseFloat(d[0].trim()),E=parseFloat(d[1].trim()),2<d.length&&(v=parseInt(d[2],10)),3<d.length&&(Rg=Fh(d[3].trim())),4<d.length&&(Ca=d[4].trim()),u=!0));c=c.split(" ");r=parseInt(c[0].trim(),10);p=parseInt(c[1].trim(),10);x=p-r;kf=parseFloat(c[2].trim());C=parseFloat(c[3].trim());m=parseFloat(c[4].trim());D=parseFloat(c[5].trim());
lf=parseFloat(c[6].trim());A=parseFloat(c[7].trim());I=G=255;9<c.length&&(I=parseFloat(c[8].trim()),G=parseFloat(c[9].trim()));for(c=r;c<=p;c++)0===x?(Ua[w][r]=kf,Va[w][r]=m,Wa[w][r]=lf,Kd[w][r]=I):(Ua[w][c]=Math.round(kf+(C-kf)*(c-r)/x),Va[w][c]=Math.round(m+(D-m)*(c-r)/x),Wa[w][c]=Math.round(lf+(A-lf)*(c-r)/x),Kd[w][c]=Math.round(I+(G-I)*(c-r)/x)),Lc[w][c]=Ca,Kc[w][c]=Rg,Ub[w][c]=v,u&&(rb[w][c]=F+(E-F)*(c-r)/x)}}-1!=mb&&l[mb].checked&&(xa.disabled=!1);Jc=!0;aa()};g.open("get",b,!0);g.send()}else aa()}
function aa(){var b=e.sprite_filenames;if(null!=b){var a=b.split(",");mf=0;fa=[];b=e.sprite_images_offset;Mc=-1;null!=b&&(Mc=parseInt(b,10)-1);for(b=0;b<a.length;b++){fa[b]=new Image;fa[b].gotit=!1;fa[b].inx=b;fa[b].fromfile=!0;var d="/";0<a[b].indexOf("?")&&(d="?");fa[b].zoomme=0<a[b].indexOf(d+"zoom");fa[b].anim=0<a[b].indexOf(d+"animate");d=a[b].indexOf(d);0<d&&(a[b]=a[b].substring(0,d));fa[b].onload=function(){fa[this.inx].gotit=!0;mf++;mf==a.length&&Y()};fa[b].src=a[b].trim()}}else Y()}function Y(){for(var b=
Object.keys(e),a=0;a<b.length;a++)B(b[a],"hotspot")&&Yc("hotspot="+e[b[a]]);$c?HAniS.getFOF():(rc=!0,gc())}function H(b){var a=new XMLHttpRequest;rb=[];re=[];Kc=[];var d=" ";Lc=[];var c="Value=";Ub=[];var n=1;Nc=[];nf=[];Ua=[];Va=[];Wa=[];var e,k=-1;w=-1;var h=0;a.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var q=a[b].replace(/\s+/g," ").trim().split(","),f=q[0].split(" ");if(0==f[0].indexOf("*"))w++,rb[w]=[],Lc[w]=[],Kc[w]=[],Ub[w]=[],Ua[w]=[],
Va[w]=[],Wa[w]=[],nf[w]=[],Nc[w]=[],k=-1,re[w]=1<q.length?q[1].trim():"None",h=1;else if(0!=h){k++;var g=Array(3);rb[w][k]=parseFloat(f[0]);Ua[w][k]=parseInt(f[1].trim(),10);Va[w][k]=parseInt(f[2].trim(),10);Wa[w][k]=parseInt(f[3].trim(),10);0!=k&&(g[0]=Ua[w][k]-Ua[w][k-1],g[1]=Va[w][k]-Va[w][k-1],g[2]=Wa[w][k]-Wa[w][k-1],e=0,Math.abs(g[1])>Math.abs(g[e])&&(e=1),Math.abs(g[2])>Math.abs(g[e])&&(e=2),nf[w][k-1]=e,Nc[w][k-1]=g,0==Nc[w][k-1][e]&&(Nc[w][k-1][e]=1));1<q.length&&(0==q[1].trim().indexOf('"')?
(n=-1,q=q[1].trim(),c=q.substr(1,q.length-2),d=""):(n=parseInt(q[1],10),2<q.length&&(d=Fh(q[2].trim())),3<q.length&&(c=q[3].trim())));Lc[w][k]=c;Ub[w][k]=n;Kc[w][k]=d}}Jc=!0};a.open("get",b,!0);a.send()}function wb(b){b=b.split(",");var a=b[0].trim();"PS"===a?(Vb=new Xh,Vb.init(b)):"CE"==a?(Vb=new Yh,Vb.init(b)):"LCC"==a?(Vb=new Zh,Vb.init(b)):(Vb=null,of=parseFloat(b[0]),Tg=parseFloat(b[1]),Gh=parseFloat(b[2]),Hh=parseFloat(b[3]))}function Vf(b){var a=new XMLHttpRequest;a.onload=function(){f(this.responseText.split("\n"))};
a.open("get",b+"?"+Math.round(1E5*Math.random()),!0);a.send()}function Oe(b){var a;if(null!=bd){for(a=0;a<bd.length;a++)-1!=bd[a].indexOf(b)&&(l[a].checked=!1);for(a=0;a<bd.length;a++)xc(a)}}function Ia(b){pf=Array(b.length);for(var a=0;a<b.length;a++){var d=60*Math.floor(b[a]/100)+Math.floor(b[a])%100;0===a&&(Wb=d);var c=d-Wb;0>c&&(c=d+1440-Wb);pf[a]=c;J("times s="+d+"  min="+pf[a])}Wb+=me;1440<=Wb&&(Wb-=1440);0>Wb&&(Wb+=1440);J("Starting minute = "+Wb)}function fc(b,a){if(0!=b)for(var d=0;d<b;d++)0==
l[Da[d].overlay].isGhost&&(l[Da[d].overlay].parentNode.style.visibility=a)}function Sa(){0!=sb?fc(sb,"visible"):0!=Ug&&fc(Ug,"hidden");rc=!0;gc()}function td(b,a){gd||(Ab.height=a,Ab.width=b,lc.height=a,lc.width=b,Ld.height=a,Ld.width=b,se.height=a,se.width=b,Md=se.getContext("2d"),T=b,X=a,te=T/2-100,ue=X/2-10,C=1*ka/T,m=1*ca/X,Vg&&(Vg=!1,null!=Wg&&Wg()),Ta.style.height=X+"px",Ta.style.width=T+"px",sc.style.height=X+"px",sc.style.width=T+"px",hd.style.height=X+"px",hd.style.width=T+"px",vd(y,!1))}
function gc(){var b,a,d;void 0!=ve&&ve(!1);var c="?"+Math.round(1E4*Math.random()),n=[];n[0]=tc;for(b=1;b<y;b++)n[b]=b<=tc?b-1:b;Ea=Array(y);Cb=Fa=0;Xg=gf;qf&&(hb.max=y);gd&&(id||Dc)&&(Xb=[],Ma=[],Oc=[],rf=[],we=[]);null!=xa&&(xa.selectedIndex=0);for(var e=0;e<y;e++){b=n[e];gd&&(id||Dc)&&(Xb[b]=t("canvas"),Ma[b]=t("canvas"));Ea[b]=new Image;Ea[b].gotit=!1;Ea[b].frameNum=b;Ea[b].onerror=function(){Fa++};Ea[b].onload=function(){gd&&(ca=this.height,ka=this.width,Xa=ca,Ya=ka,gd=!1,fg?af?HAniS.setWindowSize(z.offsetWidth,
z.offsetHeight):td(T,X):td(ka,ca),Lg&&("auto"==qc&&(qc=(C+m)/2,Id=-1),Xa/=qc,Ya/=qc,0>Id&&(Id=ka/2,Kg=ca/2),P=Math.round(Id-ka/2/qc),O=Math.round(Kg-ca/2/qc),F=E=qc,1!=qc&&(ta=!1,HAniS.toggleZooming())));if(0<xe&&!jd){sf.height=ca;sf.width=ka;Nd=sf.getContext("2d");Nd.clearRect(0,0,T,X);for(var b=0;b<Na.length;b++){for(var e=Na[b].ctx.getImageData(0,0,Na[b].width,Na[b].height).data,k=Nd.getImageData(Na[b].xmin,Na[b].ymin,Na[b].width,Na[b].height),q=3;q<e.length;q+=4)0!=e[q]&&(k.data[q]=b+1);Nd.putImageData(k,
Na[b].xmin,Na[b].ymin)}ta||(ib=!0);F==ye&&(ib=!0);jd=!0}if(rc){rc=!1;G=Ab.getContext("2d");G.imageSmoothingEnabled=zd;G.fillStyle="blue";G.font="bold 20px Arial";g=lc.getContext("2d");g.imageSmoothingEnabled=zd;Oa=Array(y);vd(y,!0);ze&&!Pa?va(qa(tc)):va(qa(r));if(0<la)for(L=Array(y),q=0;q<y;q++)for(d=n[q],L[d]=Array(la),a=0;a<la;a++)L[d][a]=new Image,L[d][a].gotit=!1,L[d][a].frameNum=d,L[d][a].overlayNum=a,L[d][a].onerror=function(){Fa++},L[d][a].onload=function(){this.gotit=!0;var a=this.frameNum;
Fa++;ua();!je||this.height==ca&&this.width==ka?this.overlayNum==Bd-1&&(Oa[this.frameNum]=0):(this.gotit=!1,J("Bad image size:"+this.src));if(Dc&&this.gotit&&this.overlayNum==mb)Xb[a].height=this.height,Xb[a].width=this.width,Od=Xb[a].getContext("2d"),Od.drawImage(this,0,0),rf[a]=Od.getImageData(0,0,this.width,this.height).data,Ma[a].height=this.height,Ma[a].width=this.width,Oc[a]=Ma[a].getContext("2d"),Oc[a].drawImage(this,0,0),we[a]=Oc[a].getImageData(0,0,this.width,this.height),L[a][this.overlayNum]=
null,L[a][this.overlayNum]=Ma[a],L[a][this.overlayNum].gotit=!0;else if(this.gotit&&l[this.overlayNum].hotspotIndex){var b=t("canvas");b.height=this.height;b.width=this.width;var c=b.getContext("2d");c.drawImage(this,0,0);var d=c.getImageData(0,0,this.width,this.height).data,n=d.length;var q=this.overlayNum;var e;for(e=0;e<n;e+=4)if(0!=d[e]){0==jb&&(kb=[]);var k=d[e];var h=Math.floor(e/4/b.width);c=Math.floor(e/4%b.width);kb[jb]=new Zc(c,h,"spritefn",k,"pan",null,null,q,a,null);jb++}}else if(this.gotit&&
jg&&(!cf||cf&&ng[this.overlayNum])){b=t("canvas");b.height=this.height;b.width=this.width;c=b.getContext("2d");c.drawImage(this,0,0);h=c.getImageData(0,0,this.width,this.height);d=h.data;n=d.length;for(e=0;e<n;e+=4)d[e]===kg&&d[e+1]===lg&&d[e+2]===mg&&(d[e+3]=0);c.putImageData(h,0,0);L[a][this.overlayNum]=null;L[a][this.overlayNum]=b;L[a][this.overlayNum].gotit=!0}this.gotit&&bf[this.overlayNum]?(tf.clearRect(0,0,T,X),tf.drawImage(L[a][this.overlayNum],0,0,T,X)):this.gotit&&hg[this.overlayNum]&&null!=
K&&(b=t("canvas"),b.height=ca,b.width=ka,8>K.length&&(K[4]=0,K[5]=0,K[6]=ka,K[7]=ca),c=b.getContext("2d"),c.imageSmoothingEnabled=ig,c.drawImage(this,K[0],K[1],K[2],K[3],K[4],K[5],K[6],K[7]),L[a][this.overlayNum]=null,L[a][this.overlayNum]=b,L[a][this.overlayNum].gotit=!0,null!=nb&&nb[this.overlayNum]&&(L[a][this.overlayNum].origImage=this))},b=ha[d][a],void 0!=Ad[a+1]&&(b=Ad[a+1],b>=y&&(b=y-1),b=ha[b][a]),void 0==Pd||Pd[a]||(b+=c),L[d][a].src=b,Cb++;if(null!=Pc)for(Yb=[],a=0;a<Pc.length;a++)Yb[a]=
new Image,Yb[a].gotit=!1,Yb[a].onerror=function(a){Fa++},Yb[a].onload=function(a){a.currentTarget.gotit=!0;Fa++;ua()},Yb[a].src=Pc[a],Cb++;if(null!=Ga&&0<Ga.length)for(sa=[],a=0;a<Ga.length;a++)if(void 0!=Ga[a])for(sa[a]=[],d=0;d<Ga[a].length;d++)for(sa[a][d]=[],q=0;q<y;q++)Ih(Ga[a][d],"/")?(b=ha[q][a].lastIndexOf("/"),b=ha[q][a].substring(0,b+1)+Ga[a][d]+ha[q][a].substring(b+1),sa[a][d][q]=new Image,sa[a][d][q].gotit=!1,sa[a][d][q].onerror=function(a){Fa++;ua()},sa[a][d][q].onload=function(a){a.currentTarget.gotit=
!0;Fa++;ua()},sa[a][d][q].src=b,Cb++):0===q?(sa[a][d][0]=new Image,sa[a][d][0].gotit=!1,sa[a][d][0].onerror=function(a){Fa++;ua()},sa[a][d][0].onload=function(a){a.currentTarget.gotit=!0;Fa++;ua()},sa[a][d][0].src=Ga[a][d],Cb++):sa[a][d][q]=sa[a][d][0]}!je&&0!=this.height&&0!=this.width||this.height==ca&&this.width==ka?(this.gotit=!0,0==Bd&&(Oa[this.frameNum]=0)):(this.gotit=!1,J("Image has invalid size:"+this.src));id&&this.gotit&&(q=this.frameNum,Xb[q].height=this.height,Xb[q].width=this.width,
Od=Xb[q].getContext("2d"),Od.drawImage(this,0,0),rf[q]=Od.getImageData(0,0,this.width,this.height).data,Ma[q].height=this.height,Ma[q].width=this.width,Oc[q]=Ma[q].getContext("2d"),Oc[q].drawImage(this,0,0),we[q]=Oc[q].getImageData(0,0,this.width,this.height),Ea[q]=null,Ea[q]=Ma[q],Ea[q].gotit=!0);Fa++;ua();wg||HAniS.resetZoom();Qc=!0;Jh||(Jh=!0,ya=!1,p());R(Pa)};var k=za[b];void 0!=Ad[0]&&(k=Ad[0],k>=y&&(k=y-1),k=za[k]);ef||(k+=c);Ea[b].src=k;Cb++}Rc=Db=!1;S()}function da(b,a,d,c,n,q){b.label_on=
d;b.label_off=c;fb&&(b.className=q);d=null;c=e[a+"_labels"];null==c&&(c=e[a+"_label"]);null!=c&&(c=c.split(","),b.label_on=c[0].trim(),1<c.length&&(b.label_off=c[1].trim()),2<c.length&&(d="width:"+c[2].trim()+"px;"));null!=n&&(b.title=n);b.innerHTML=b.label_on;n=a=c=e[a+"_style"];null!=c&&(c=c.split("&"),1<c.length&&(a=c[0],n=c[1]));b.style_on=(null!=d?d:"")+uc+a;b.style_off=(null!=d?d:"")+uc+n;null!=b.style_on&&1<b.style_on.length?b.setAttribute("style",b.style_on):(b.style_on=null,b.style_off=null)}
function xb(b,a){uc=e.buttons_style;null==uc&&(uc="");var d=null,c=null;d=a?e.controls_tooltip:e.bottom_controls_tooltip;var n=b.split(",");if(null!=d){var q=d.split(",");q.length!=n.length&&(J("!!! Number of tooltips must equal number of controls!"),q=d=null)}for(b=0;b<n.length;b++){var k=null!=d?q[b]:null;var h=n[b].trim();c=h.indexOf("/");if(0===c||0===b){0===c&&(h=h.substring(1));D=t("div");D.align=wd;var f=e.controls_style;null!=f?D.setAttribute("style",f):D.setAttribute("style","position:relative;padding:2px;width:100%;");
a?(z.insertBefore(D,Ta),uf=D):(f=e.bottom_controls_style,null!=f&&D.setAttribute("style",f),z.appendChild(D),vf=D)}"enhance"==h.trim()&&(xa=t("select"),c=e.enhance_style,null!=c&&xa.setAttribute("style",c),null!=k&&(xa.title=k),c=t("option"),c.innerHTML="Pick Enhancement",c.value=-1,xa.add(c),xa.addEventListener("change",HAniS.doEnhance,!1),id=!Dc,xa.disabled=id?!1:!0,D.appendChild(xa));"startstop"==h&&(Bb=t("button"),da(Bb,"startstop","Animar","Pausar",k,"startstop start"),Bb.addEventListener("click",
HAniS.toggleIsLooping,!1),D.appendChild(Bb));"looprock"==h&&(Qd=t("button"),da(Qd,"looprock","Rock","Loop",k,"looprock rock"),wf=1,Qd.addEventListener("click",HAniS.toggleLoopRock,!1),D.appendChild(Qd));"extrap"==h&&(Zb=t("button"),da(Zb,"extrap","Enable Extrap","Disable Extrap",k,"extrap"),Zb.addEventListener("click",HAniS.toggleExtrap,!1),D.appendChild(Zb));B(h,"location")&&(kd=t("button"),da(kd,"location","Show Loc","Hide Loc",k,"location"),0<h.indexOf("/on")?(I(kd,!1,"location off"),ld=!0,Aa.push(z.style.cursor),
z.style.cursor=he):(ld=!1,z.style.cursor=Aa.pop()),kd.addEventListener("click",function(){(ld=!ld)?(I(kd,!1,"location off"),Aa.push(z.style.cursor),z.style.cursor=he):(I(kd,!0,"location on"),z.style.cursor=Aa.pop());S()},!1),D.appendChild(kd));"distance"==h&&($b=t("button"),da($b,"distance","Show dist","Hide dist",k,"distance"),kc=ge=!1,$b.addEventListener("click",function(){(kc=!kc)?(I($b,!1,"distance off"),Aa.push(z.style.cursor),z.style.cursor=Te):(I($b,!0,"distance on"),z.style.cursor=Aa.pop())},
!1),D.appendChild($b));B(h,"probe")&&(md=t("button"),da(md,"probe","Show probe","Hide probe",k,"probe"),0<h.indexOf("/on")?(I(md,!1,"probe off"),Mb=!0,Aa.push(z.style.cursor),z.style.cursor=ie):(Mb=!1,z.style.cursor=Aa.pop()),md.addEventListener("click",function(){(Mb=!Mb)?(I(md,!1,"probe off"),Aa.push(z.style.cursor),z.style.cursor=ie):(I(md,!0,"probe on"),z.style.cursor=Aa.pop())},!1),D.appendChild(md));"mark"==h&&(Sc=t("button"),da(Sc,"mark","Mark","Stop Mark",k,"mark"),Rd=!0,Sc.addEventListener("click",
function(){tb=!tb;ma=[];tb?(nd=0,I(Sc,!1,"mark off"),null!=wa&&(wa.disabled=!0),Aa.push(z.style.cursor),z.style.cursor=Ue):(I(Sc,!0,"mark on"),null!=wa&&(wa.disabled=!1),nd=-1,z.style.cursor=Aa.pop());S()},!1),Kh=new zb("black","white",jf,"black",20,5,5),Yg=new zb("black","white",jf,"black",20,5,5),D.appendChild(Sc));"refresh"==h&&(qe=t("button"),da(qe,"refresh","Refresh",null,k,"refresh"),qe.addEventListener("click",HAniS.reloadFOF,!1),D.appendChild(qe));"restore"==h&&(xf=t("button"),da(xf,"restore",
"Restore",null,k,"restore"),xf.addEventListener("click",function(a){for(a=0;a<l.length;a++)l[a].checked=l[a].restorableState;for(a=0;a<l.length;a++)xc(a)},!1),D.appendChild(xf));"setframe"==h&&(hb=t("input"),fb&&(hb.className="setframe"),hb.type="range",hb.min=1,hb.max=100,hb.value=1,Ae="Frame #*",null!=k&&(hb.title=k),f=e.setframe_label,null!=f&&(Ae=f),Sd=t("span"),Sd.innerHTML=Ae.replace("*",1),c="display:block;vertical-align:middle;"+e.setframe_style,hb.setAttribute("style",c),c=t("span"),c.setAttribute("style",
"display:inline-block;vertical-align:top;"),Sd.setAttribute("style","display:block;vertical-align:middle;"+e.setframe_label_style),c.appendChild(Sd),c.appendChild(hb),D.appendChild(c),hb.addEventListener("input",function(a){R(!1);a=parseInt(hb.value,10)-1;0<=Oa[a]&&(va(a),Sd.innerHTML=Ae.replace("*",r+1));ea()},!1),qf=!0);"framelabel"==h&&(Ha=t("button"),fb&&(Ha.className="framelabel"),Ha.innerHTML="",null!=k&&(Ha.title=k),Za=null,f=e.frame_labels,null!=f&&(Za=f.split(","),Ha.innerHTML=Za[0]),c=uc+
e.framelabel_style,null!=c&&Ha.setAttribute("style",c),c=e.framelabel_position,null!=c&&(c=c.split(","),Ha.style.position="absolute",Ha.style.left=z.offsetLeft+parseInt(c[0],10)+"px",Ha.style.top=z.offsetTop+parseInt(c[1],10)+"px"),D.appendChild(Ha));if("autorefresh"==h||"autorefresh/off"==h)null!=Bc&&clearInterval(Bc),Ic=t("button"),da(Ic,"autorefresh","Desactivar Actualizacion Automatica","Activar Actualizacion Automatica",k,"autorefresh"),Ic.addEventListener("click",HAniS.toggleAutoRefresh,!1),yd=!1,D.appendChild(Ic),"autorefresh"==
h?HAniS.toggleAutoRefresh():I(Ic,!1,"autotoggle off");"backward"==h&&(pb=t("button"),da(pb,"backward","<","<",k,"step back"),pb.addEventListener("click",function(){R(!1);Lb(-1);ea()},!1),D.appendChild(pb));"forward"==h&&(qb=t("button"),da(qb,"forward",">",">",k,"step forward"),qb.addEventListener("click",function(){R(!1);Lb(1);ea()},!1),D.appendChild(qb));if("step"==h){c=e.step_labels;var g=null!=c?c.split(","):["<",">"];pb=t("button");fb&&(pb.className="step back");pb.innerHTML=g[0];pb.addEventListener("click",
function(){R(!1);Lb(-1);ea()},!1);c=uc+e.step_style;null!=c&&pb.setAttribute("style",c);null!=k&&(pb.title=k);D.appendChild(pb);qb=t("button");fb&&(qb.className="step forward");qb.innerHTML=g[1];qb.addEventListener("click",function(){R(!1);Lb(1);ea()},!1);null!=c&&qb.setAttribute("style",c);null!=k&&(qb.title=k);D.appendChild(qb)}"first"==h&&(Eb=t("button"),da(Eb,"first","|<","|<",k,"firstlast first"),Eb.addEventListener("click",function(){R(!1);va(qa(0));ea()},!1),D.appendChild(Eb));"last"==h&&(Fb=
t("button"),da(Fb,"last",">|",">|",k,"firstlast last"),Fb.addEventListener("click",function(){R(!1);va(qa(y-1));ea()},!1),D.appendChild(Fb));"firstlast"==h&&(c=e.firstlast_labels,g=null!=c?c.split(","):["<<",">>"],Eb=t("button"),fb&&(Eb.className="firstlast"),Eb.innerHTML=g[0],Eb.addEventListener("click",function(){R(!1);va(qa(0));ea()},!1),c=uc+e.firstlast_style,null!=c&&Eb.setAttribute("style",c),null!=k&&(Eb.title=k),D.appendChild(Eb),Fb=t("button"),fb&&(Fb.className="firstlast"),Fb.innerHTML=
g[1],Fb.addEventListener("click",function(){R(!1);va(qa(y-1));ea()},!1),null!=c&&Fb.setAttribute("style",c),null!=k&&(Fb.title=k),D.appendChild(Fb));"setspeed"==h?(Gb=t("input"),fb&&(Gb.className="setspeed"),Gb.type="range",Gb.min=Rb,Gb.max=Hc,Gb.value=Hc-gb,null!=k&&(Gb.title=k),c="vertical-align:middle;"+e.setspeed_style,Gb.setAttribute("style",c),Gb.addEventListener("input",function(a){gb=Hc-parseInt(Gb.value,10)+30;R(!0);ea()},!1),D.appendChild(Gb)):"speed"==h&&(c=e.speed_labels,g=null!=c?c.split(","):
["-","+"],Sb=t("button"),fb&&(Sb.className="speed slower"),Sb.innerHTML=g[0],Sb.addEventListener("click",function(){gb+=hf;Tb.disabled=!1;gb>Hc&&(gb=Hc,Sb.disabled=!0)},!1),c=uc+e.speed_style,null!=c&&Sb.setAttribute("style",c),null!=k&&(Sb.title=k),D.appendChild(Sb),Tb=t("button"),fb&&(Tb.className="speed faster"),Tb.innerHTML=g[1],Tb.addEventListener("click",function(){gb-=hf;Sb.disabled=!1;gb<Rb&&(gb=Rb,Tb.disabled=!0)},!1),null!=c&&Tb.setAttribute("style",c),null!=k&&(Tb.title=k),D.appendChild(Tb));
"zoom"==h&&(wa=t("button"),da(wa,"zoom","Zoom","Un-zoom",k,"zoom off"),wa.addEventListener("click",HAniS.toggleZooming,!1),D.appendChild(wa),ta=!1);if("annotate"==h){Td=t("button");da(Td,"annotate","Herramientas","Cerrar Herramientas",k,"annotate");ia=t("div");ia.setAttribute("style","position:absolute;height:140px;width:200px;top:20px;left:20px;z-index:15;visibility:hidden;background-color:lightgray;border-width:4px;border-style:solid;border-color:black;border-radius:5px;padding:10px;font-family:Arial;font-size:12px;color:black;");
ia.title="Drag this box around.  Select attributes, then go onto the image and click & drag";Tc=Uc=20;Be=Hb=!1;Zg=3;$g=11;Vc=Ud=0;u=[];ia.style["touch-action"]="none";var p=function(a){Uc=a.clientX-Vc;Tc=a.clientY-Ud;ia.style.top=Tc+"px";ia.style.left=Uc+"px"};ia.addEventListener("mousedown",function(a){if(0!=a.clientX||0!=a.clientY)Be=!0,Vc=a.clientX-Uc,Ud=a.clientY-Tc},!1);ia.addEventListener("mouseup",function(a){Be=!1},!1);ia.addEventListener("mouseout",function(a){Be&&p(a)},!1);ia.addEventListener("mousemove",
function(a){Be&&p(a)},!1);window.PointerEvent?(ia.addEventListener("pointerdown",function(a){"mouse"!=a.pointerType&&(Vc=a.clientX-Uc,Ud=a.clientY-Tc)},!1),ia.addEventListener("pointermove",function(a){"mouse"!=a.pointerType&&(0==Vc&&(Vc=a.clientX,Ud=a.clientY),p(a))},!1)):ia.addEventListener("touchmove",function(a){a=a.changedTouches[0];0==Vc&&(Vc=a.clientX,Ud=a.clientY);p(a)},!1);Td.addEventListener("click",function(){if(Hb=!Hb){u=[];Uc=z.offsetLeft;Tc=z.offsetTop;var a=e.annotate_position;null!=
a&&(a=a.split(","),Uc+=parseInt(a[0],10),Tc+=parseInt(a[1],10));ia.style.top=Tc+"px";ia.style.left=Uc+"px";ia.style.visibility="visible";I(Td,!1,"annotate off");Lh=ta;ta=!1;null!=wa&&(wa.disabled=!0)}else ia.style.visibility="hidden",I(Td,!0,"annotate on"),ta=Lh,null!=wa&&(wa.disabled=!1);S()},!0);Vd=ah("Color Negro Blanco Rojo Verde Azul Amarillo Naranja Cyan Magenta".split(" "),"black black white red green blue yellow orange cyan magenta".split(" "),function(a){});vc=ah("Ancho 1 2 3 4 5 6 7 8 10 12 14 16 18 20 24 28 32 36 38".split(" "),
[1,1,2,3,4,5,6,7,8,10,12,14,16,18,20,24,28,32,36,38],function(a){6==Wd.selectedIndex?$g=vc.selectedIndex:Zg=vc.selectedIndex});vc.title="Seleccione tamaño";Wd=ah("Tipo Flecha Circulo Caja Poligono Dibujo Texto".split(" "),[-1,0,1,2,3,4,5],function(a){6==Wd.selectedIndex?(Ib.focus(),Ib.select(),vc.selectedIndex=$g):vc.selectedIndex=Zg;0==Vd.selectedIndex&&(Vd.selectedIndex=2)});c=t("button");c.style.width="70px";c.style.margin="5px";c.innerHTML="Borrar";c.title="Borrar ultimo";c.addEventListener("click",
function(){0<u.length&&(u.pop(),S())},!1);Ib=t("input");Ib.type="text";Ib.style.width="150px";Ib.style.margin="5px";Ib.title="Ingrese texto y luego cliquee en la imagen";Ib.value="Text input";g=e.annotate_defaults;null!=g&&(g=g.split(","),Wd.selectedIndex=parseInt(g[0],10),1<g.length&&(Vd.selectedIndex=parseInt(g[1],10)),2<g.length&&(vc.selectedIndex=parseInt(g[2],10)),3<g.length&&(Ib.value=g[3].trim()));g=t("div");g.innerHTML="Herramientas";var Ca=t("div");Ca.appendChild(Wd);Ca.appendChild(Vd);
var v=t("div");v.appendChild(vc);v.appendChild(c);c=t("div");c.appendChild(Ib);ia.appendChild(g);ia.appendChild(Ca);ia.appendChild(v);ia.appendChild(c);D.appendChild(Td);z.appendChild(ia)}"saveall"==h&&(yf=t("button"),da(yf,"saveall","SaveAll","SaveAll",k,"saveall"),bh=e.saveall_prompt,ac=e.saveall_filename,c=e.saveall_list,ch=null==c?["0"]:c.split(","),yf.addEventListener("click",function(){for(var a=0;a<ch.length;a++)for(var b=parseInt(ch[a],10),c=0;c<za.length;c++){0===c&&null!=bh&&(ac=window.prompt(bh,
ac),null!=ac&&1>ac.length&&(ac=null));var d=null==ac?"":-1!=ac.indexOf("#")?ac.replace("#",c.toString()):ac+c;var n=document.createElement("a");n.href=0==b?za[c]:ha[c][b-1];n.download=d;d=new MouseEvent("click");n.dispatchEvent(d)}},!1),D.appendChild(yf));if("capture"==h){zf=t("button");da(zf,"capture","Capture","Capture",k,"capture");var w=e.capture_prompt;Af=e.capture_filename;null==Af&&(Af="haimage.png");zf.addEventListener("click",function(){var a=Af;if(null!=w&&(a=window.prompt(w,a),null==a))return;
var b=t("canvas");b.height=Ab.height;b.width=Ab.width;var c=b.getContext("2d");Rd=!1;S();c.drawImage(Ab,0,0);c.drawImage(lc,0,0);Rd=!0;b.toBlob(function(b){var c=URL.createObjectURL(b),d=document.createElement("a");d.href=c;d.download=a;c=new MouseEvent("click");d.dispatchEvent(c);setTimeout(function(){URL.revokeObjectURL(b)},3E4)})},!1);D.appendChild(zf)}"show"==h&&(Bf=t("button"),da(Bf,"show","Show","Show",k,"show"),Cf=e.show_prompt,Mh=e.show_image_file,null==Cf&&(Cf="Right-click to save or copy the image<br> <font size='-1'>(to save in some browsers, you may need to first 'Open in New Tab')</font> <p>"),
Bf.addEventListener("click",function(){if(Mh)window.open(za[r]);else{var a=Ab.toDataURL("image/png;base64;");var b=window.open();b.document.write(Cf+"<img src="+a+"></img>")}},!1),D.appendChild(Bf));"toggle"==h&&(Oa=[],c=e.toggle_size,null!=c?(c=c.split(","),od=parseInt(c[0],10),Ce=parseInt(c[1],10),De=parseInt(c[2],10)):(Ce=od=10,De=3),dh="red",eh="blue",fh="orange",gh=!1,B(e.toggle_layout_width,"t")&&(gh=!0),c=e.toggle_colors,null!=c&&(c=c.split(","),eh=c[0].trim(),dh=c[1].trim(),fh=c[2].trim()),
ub=t("div"),ub.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;"),ub.style.backgroundColor=D.style.backgroundColor,ub.align=wd,hh=new PEvs(ub,null,null,null,null,HAniS.togclick,null),Wc=t("canvas"),Wc.height=2*Ce,Df=Wc.getContext("2d"),ub.appendChild(Wc),a?z.insertBefore(ub,Ta):z.appendChild(ub),c=e.toggle_onoff,Ee=null,null!=c&&(Ee=c.split(",")),
Ef=!0,null!=k&&(ub.title=k));if("overlay"==h){l=[];h=e.overlay_tooltip;k=null;null!=h&&(k=h.split(","));h=e.overlay_radio;c=null;null!=h&&(c=h.split(","));Ca=e.overlay_labels_color;g=null;null!=Ca&&(g=Ca.split(","));Pd=[];v=e.overlay_caching;Ca=null;null==v&&(v=e.overlay_static);null!=v&&(Ca=v.split(","));var x=!0;null!=e.overlay_nonewdiv&&(x=!1);for(v=0;v<Pb.length;v++){var m=Pb[v].trim();if(0==v||0==m.indexOf("/"))0==m.indexOf("/")&&(m=m.substr(1)),x?(Jb=t("div"),ih++,Jb.align="center",a?z.insertBefore(Jb,
Ta):z.appendChild(Jb)):(Jb=t("span"),D.appendChild(Jb)),f=e.overlay_labels_style,null!=f&&Jb.setAttribute("style",f);var C=!1;f=m.length;0<m.indexOf("/on")&&m.indexOf("/on")==f-3&&(C=!0,m=m.substr(0,f-3));var A=!1;0<m.indexOf("/always")&&m.indexOf("/always")==f-7&&(A=C=!0);var F=!1;0<m.indexOf("/hidden")&&(F=!0);var E=!1;0<m.indexOf("/hotspots")&&(E=!0,m=m.substr(0,m.indexOf("/")));null!=Ca?B(Ca[v],"y")||B(Ca[v],"t")?Pd[v]=!0:Pd[v]=!1:Pd[v]=!0;l[v]=t("input");l[v].type="checkbox";l[v].value=m;l[v].id=
m;l[v].showMe=!(A&F)&!E;var G="vertical-align:middle;";f=e.checkbox_style;null!=f&&(G+=f);l[v].setAttribute("style",G);l[v].checked=C;l[v].restorableState=C;l[v].name=0;l[v].hotspotIndex=E;null!=xa&&v==mb&&l[v].checked&&(xa.disabled=!1);null!=nc&&!nc[v]&&C&&(ad=!1);l[v].addEventListener("click",HAniS.overClick,!1);null!=h&&(f=c[v].indexOf("/"),-1!=f&&(l[v].name=c[v].substr(f+1).trim()),B(c[v],"t")&&(l[v].type="radio",-1==f&&(l[v].name="all")));l[v].isGhost=!0;A||F||(null!=k&&(l[v].title=k[v]),f=t("label"),
f.htmlFor=m,null!=k&&(f.title=k[v]),f.innerHTML=m,f.name=l[v].name,m="vertical-align:middle;",null!=g&&(m=m+"color:"+g[v]+";"),f.setAttribute("style",m),m=t("span"),A="10",null!=ke&&(A=10+ke[v]),m.setAttribute("style","margin-left:"+A+"px;"),m.appendChild(l[v]),m.appendChild(f),Jb.appendChild(m),l[v].isGhost=!1)}if(null==Qb)for(Qb=Array(Pb.length),v=0;v<Pb.length;v++)Qb[v]=0;else for(v=0;v<Pb.length;v++)xc(v)}}Pa=!0;ze=null;f=e.start_looping;null!=f&&(c=f.split(","),B(c[0],"f")&&(Pa=!1),1<c.length&&
(tc=parseInt(c[1],10)-1,isNaN(tc)&&(tc=0),r=tc),2<c.length&&(B(c[2],"t")&&(ze=!0),B(c[2],"f")&&(ze=!1)));R(Pa)}function xc(b){var a;if(0>Qb[b]){var d=!1;for(a=0;a<Pb.length;a++)Qb[a]!=-Qb[b]||d||(d=l[a].checked);l[b].checked=d}}function Yc(b){0==jb&&(kb=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");var a=b[4].trim(),d=b[4].indexOf("/"),c=b[4].indexOf("?"),n=-1,e=-1;-1!=d&&(n=parseInt(b[4].substring(d+1),10)-1,a=a.substring(0,d));-1!=c&&(e=parseInt(b[4].substring(c+1),10)-1,c<d||-1==d)&&(a=a.substring(0,
c));kb[jb]=new Zc(parseInt(b[0].trim(),10),parseInt(b[1].trim(),10),b[2].trim(),b[3].trim(),a.toLowerCase(),b[5].trim().toLowerCase(),b[6].trim(),n,e,8==b.length?b[7].trim():null);jb+=1}function Pe(b){0==xe&&(Na=[],na=null);var a=b.substr(b.indexOf("=")+1).trim().split("(");b=a[0].split(",");var d=b[0].trim();0==d.indexOf("0x")&&(d="#"+d.substring(2));Na[xe]=new yc(d,b[1].trim(),b[2].trim(),b[3].trim(),a[1].trim());xe+=1}function cb(b){0==sb&&(Da=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");
Da[sb]=new zc(parseInt(b[0],10)-1,parseInt(b[1],16),b[2].trim(),b[3].trim(),5==b.length?b[4].trim():"Click for details");sb+=1}function yc(b,a,d,c,n){this.color=b;this.alpha=1;7<this.color.length&&(this.alpha=parseInt(this.color.substring(7),16)/255,this.color=this.color.substring(0,7),.1>this.alpha&&(this.alpha=.1));this.action=a;this.value=d;this.tip=c;this.poly=n;b=n.split(",");this.xy=[];this.ymin=this.xmin=9999;for(a=this.ymax=this.xmax=0;a<b.length;a++)this.xy[a]=parseInt(b[a].trim(),10),0==
a%2?(this.xy[a]<this.xmin&&(this.xmin=this.xy[a]),this.xy[a]>this.xmax&&(this.xmax=this.xy[a])):(this.xy[a]<this.ymin&&(this.ymin=this.xy[a]),this.xy[a]>this.ymax&&(this.ymax=this.xy[a]));this.height=this.ymax-this.ymin+1;this.width=this.xmax-this.xmin+1;this.can=t("canvas");this.can.height=this.height;this.can.width=this.width;this.ctx=this.can.getContext("2d");this.ctx.imageSmoothingEnabled=!1;this.ctx.fillStyle=this.color;this.ctx.globalAlpha=this.alpha;this.ctx.beginPath();this.ctx.moveTo(this.xy[0]-
this.xmin,this.xy[1]-this.ymin);for(a=2;a<this.xy.length;a+=2)this.ctx.lineTo(this.xy[a]-this.xmin,this.xy[a+1]-this.ymin);this.ctx.closePath();this.ctx.fill()}function zc(b,a,d,c,n){this.overlay=b;this.color=a;this.action=d;this.value=c;this.tip=n}function Zc(b,a,d,c,n,e,f,g,m,t){this.x0=b;this.y0=a;this.icon=null;this.isIcon=!1;if("icon"==d)this.icon=new Image,this.icon.hotspot=this,Ff=!0,this.icon.onload=function(a){this.gotit=!0;this.hotspot.x1=this.hotspot.x0+this.width;this.hotspot.y1=this.hotspot.y0+
this.height;this.hotspot.width=this.width;this.hotspot.height=this.height;this.hotspot.w2=this.width/2;this.hotspot.h2=this.height/2;this.hotspot.isIcon=!0;this.hotspot.origX=0;this.hotspot.origY=0},this.y1=this.x1=-1,this.zoomme=this.fromfile=this.anim=!1,this.icon.gotit=!1,this.icon.src=c.trim();else if("sprite"==d||"spritefn"===d){this.x0=b;this.y0=a;this.inx=parseInt(c,10)-1;Xd=!1;eg?null!=fa&&(-1!=Mc?this.inx>=Mc&&this.inx<=Mc+fa.length&&(Xd=!0):"spritefn"===d&&(Xd=!0)):Xd=!0;if(Xd){-1!=Mc&&
(this.inx-=Mc);if(this.inx>=fa.length)return null;this.x1=fa[this.inx].width+b;this.y1=fa[this.inx].height+a;this.width=fa[this.inx].width;this.height=fa[this.inx].height;this.w2=this.width/2;this.h2=this.height/2;this.origY=this.origX=0;this.icon=fa[this.inx].cloneNode();this.anim=fa[this.inx].anim;this.fromfile=fa[this.inx].fromfile;this.zoomme=fa[this.inx].zoomme;this.anim&&(this.icon.setAttribute("style","position:absolute;top:0px;left:0px;visibility:hidden;"),sc.appendChild(this.icon))}else this.x1=
Nb[this.inx]+b,this.y1=Ob[this.inx]+a,this.width=Nb[this.inx],this.height=Ob[this.inx],this.w2=Nb[this.inx]/2,this.h2=Ob[this.inx]/2,this.origX=Ye[this.inx],this.origY=Ze[this.inx],this.icon=Xe,this.zoomme=this.fromfile=this.anim=!1;Ff=this.isIcon=!0;this.icon.gotit=!0}else this.width=parseInt(d,10),this.height=parseInt(c,10),this.x1=this.width+b,this.y1=this.height+a,this.w2=this.width/2,this.h2=this.height/2;this.pan=n;this.isPan=!1;"pan"===this.pan&&(this.isPan=!0);this.action=e;this.value=f;this.overlay=
g;this.frame=m;this.tip=t}function Ja(){if(pd&&!fd){U=-1;for(var b=0;b<ja.length;b++)F>=ja[b]&&(U=b)}}function yb(){null!=Vb?$a=Vb.toLatLon(oa,pa):null!=of?($a[0]=of+(Gh-of)*pa/ca,$a[1]=Tg+(Hh-Tg)*oa/ka):($a[0]=Math.round(oa),$a[1]=Math.round(pa))}function lb(b,a){"popup"==b.action?(null!=Gf&&Gf.close(),Gf=window.open("","HAniSPopup","scrollbars=yes,width="+Ig+",height="+Hg),Gf.document.write(Gg+b.value+"</div>")):"link"==b.action?(b=b.value,yb(),b=b.replace("%LATITUDE%",$a[0].toFixed(4)),b=b.replace("%LONGITUDE%",
$a[1].toFixed(4)),b=b.replace("%FRAMENUMBER%",r+1),window.open(b,"_blank","")):"fof"==b.action&&(ba=vg,HAniS.resetZoom(),HAniS.newFOF(b.value,!0),Oe(a))}function db(){var b=Cg?Gd/F:0;P+b<Gd&&(P=Gd-b);b=Eg?Hd/F:0;P+Ya-b>ka-Hd&&(P=ka-Ya+b-Hd);b=Ag?Fd/E:0;O+b<Fd&&(O=Fd-b);b=yg?Ed/E:0;O+Xa-b>ca-Ed&&(O=ca-Xa-Ed+b);O=Math.round(O);P=Math.round(P)}function hc(b){var a=!1;b?fd?(U--,0>U?a=!0:(F=ja[U],E=ja[U])):(F-=.1*ed/C,E-=.1*ed/m):fd?(U++,U>=ja.length?(U--,ff&&(a=!0)):(F=ja[U],E=ja[U])):(!ff||F!==Gc&&E!==
Gc||(a=!0),F+=.1*ed/C,E+=.1*ed/m,F>Gc&&(F=Gc),E>Gc&&(E=Gc));a||F<=ye||E<=Fe?(F=ye,E=Fe,U=-1,oa=A,pa=x,O=P=0,Xa=ca,Ya=ka,Gd=Hd=Fd=Ed=0,jd&&(ib=!0)):(Ed=xg,Fd=zg,Hd=Dg,Gd=Bg,P=oa-A/F,O=pa-x/E,Xa=Math.floor(ca/E),Ya=Math.floor(ka/F),db(),jd&&(ib=!1));Ja()}function ic(){Ge=0;Kb=Array(2);vb=Array(2);qd=Array(2);Qa=0;dd=null;va(qa(0))}function R(b){ya=!b;HAniS.toggleIsLooping()}function Ka(b,a,d,c,n,e){Md.clearRect(0,0,T,X);Md.imageSmoothingEnabled=zd;G.imageSmoothingEnabled=zd;Md.drawImage(b,a,d,c,n,0,
0,T,X);jh=Md.getImageData(0,0,T,X);Xc=jh.data;Hf=Ua[e];If=Va[e];Jf=Wa[e];Kf=Kd[e];Nh=4*T*X;for(bc=0;bc<Nh;bc+=4)ab=Xc[bc],ab===Xc[bc+1]&&ab===Xc[bc+2]&&(Xc[bc]=Hf[ab],Xc[bc+1]=If[ab],Xc[bc+2]=Jf[ab],Xc[bc+3]=Kf[ab]);Md.putImageData(jh,0,0);G.drawImage(se,0,0,T,X)}function I(b,a,d){null!=b&&(a?(null!=b.style_on&&b.setAttribute("style",b.style_on),b.innerHTML=b.label_on):(null!=b.style_off&&b.setAttribute("style",b.style_off),b.innerHTML=b.label_off),fb&&(b.className=d))}function eb(b,a){if(!(b>=y)&&
(-2==Oa[b]&&(a=-2),Oa[b]=a,qf&&1==a&&(hb.value=b+1,Sd.innerHTML=Ae.replace("*",b+1)),Ef)){b=kh+b*(od+De);var d=fh;0==a?d=eh:-1==a?d=dh:-2==a&&(d=gg);Df.fillStyle=d;Df.fillRect(b,Ce/2,od,Ce)}}function vd(b,a){Ef&&(Wc.width=gh?parseInt(z.style.width,10):T,Df.clearRect(0,0,Wc.width,Wc.height),kh=Wc.width/2-b*(od+De)/2);for(var d=0;d<b;d++)a?-1!=Bd?eb(d,-2):null!=Ee&&"n"==Ee[d].toLowerCase().trim()?eb(d,-1):eb(d,0):eb(d,Oa[d])}function va(b){eb(r,0);r=b;eb(r,1);null!=Ha&&null!=Za&&null!=Za[r]&&(Ha.innerHTML=
Za[r]);void 0!=He&&He(r)}function qa(b){b>=y&&(b=y-1);if(0<=Oa[b])return b;var a=-1,d=b;0==d&&(a=1);for(var c=0;c<y-1;c++)if(d+=a,0<=Oa[d])return d;return b}function Lb(b){eb(r,0);var a=b;do 0<a?(a=qa(y-1),r+=1,r>a&&(Yd&&ya?(r=a,b=-b):r=qa(0))):(a=qa(0),--r,r<a&&(Yd&&ya?(r=a,b=-b):r=qa(y-1))),a=b;while(0>Oa[r]);void 0!=He&&He(r);wf=a;eb(r,1);null!=Ha&&null!=Za&&null!=Za[r]&&(Ha.innerHTML=Za[r])}function zb(b,a,d,c,n,e,f){this.bg=b;null!=b&&0==this.bg.indexOf("0x")&&(this.bg="#"+this.bg.substring(2));
this.fg=a;null!=a&&0==this.fg.indexOf("0x")&&(this.fg="#"+this.fg.substring(2));this.font=d;this.fontHeight=Math.round(1.1*parseInt(d,10));this.scolor=c;null!=c&&0==this.scolor.indexOf("0x")&&(this.scolor="#"+this.scolor.substring(2));this.sblur=n;this.sxoff=e;this.syoff=f}function La(b,a,d,c,n){g.globalAlpha=1;g.font=b.font;var e=b.fontHeight;d=d-e-6;var f=g.measureText(c).width;1==n&&(a-=f);0==n&&(a-=f/2);5>a&&(a=5);5>d&&(d=5);d+e+3>X&&(d=X-e-6);a+3+f>T&&(a=T-f-6);g.save();g.beginPath();g.fillStyle=
b.bg;null!=b.scolor&&(g.shadowColor=b.scolor,g.shadowBlur=b.sblur,g.shadowOffsetX=b.sxoff,g.shadowOffsetY=b.syoff);Ie=a-3;Lf=d;lh=f+6;Mf=e+6;g.fillRect(Ie,Lf,lh,Mf);g.closePath();g.restore();g.textBaseline="bottom";g.fillStyle=b.fg;g.fillText(c,a,d+e+3)}function S(){g.clearRect(0,0,T,X);Nf=!1;if(bb){g.beginPath();g.lineWidth=2;g.strokeStyle="white";var b=Qa;1<b&&(b=2);for(var a=0;a<b;a++)1<Qa&&(g.moveTo(Kb[0]/C,vb[0]/m),g.lineTo(Kb[1]/C,vb[1]/m)),g.moveTo(Kb[a]/C-15,vb[a]/m),g.lineTo(Kb[a]/C+15,vb[a]/
m),g.moveTo(Kb[a]/C,vb[a]/m-15),g.lineTo(Kb[a]/C,vb[a]/m+15);g.closePath();g.stroke();if(3==Qa){var d=V,c=Q;g.moveTo(d,c);g.fillStyle=oc;g.fillRect(d-2,c-2,5,5);b=rd;a=Math.round(d+Je/C*Zd*(rd-qd[1]));for(var e=Math.round(c+$d/m*Zd*(rd-qd[1])),f=0;300>f;f++){g.beginPath();g.lineWidth=1;g.strokeStyle=oc;g.moveTo(d,c);g.lineTo(a,e);g.stroke();g.beginPath();g.lineWidth=3;g.rect(a-2,e-2,5,5);g.stroke();if(3>a||a+3>T||3>e||e+3>X)break;c=Wb+b;c=100*Math.floor(c/60)+c%60;c%=2400;qg?(d="AM",1200<=c?(1300<=
c&&(c-=1200),d="PM"):100>c&&(c+=1200),d=Math.floor(c/100)+":"+Math.floor(Math.floor(c%100)/10)+Math.floor(c%10)+" "+d):(d=c+" ",1E3>c&&(d="0"+c),100>c&&(d="00"+c),10>c&&(d="000"+c));c=0;Math.abs(Of)<cd+5&&(c=45*.0174533);var k=e;0>mh*Of&&0==c&&(k=e+cd);g.font=Dd;d=d+" "+pg;var h=g.measureText(d).width;g.fillStyle=Cd;0===c?(g.fillRect(a+2,k-cd-2+c,h+4,cd+3),g.fillStyle=oc,g.textBaseline="bottom",g.fillText(d,a+5,k)):(g.save(),g.translate(a+5,e),g.rotate(c),g.fillRect(2,-2,h+4,cd+3),g.fillStyle=oc,
g.textBaseline="bottom",g.fillText(d,5,cd),g.restore());d=a;c=e;a=Math.round(d+Zd*mh);e=Math.round(c+Zd*Of);b+=W}}null!=dd&&La(df,Oh,Ph,dd,0);Rd&&(La(Bh,9999,Ng,Mg[Ge],0),nh=Ie,oh=Lf,ph=Lf+Mf)}if(tb){Rd&&(0==nd?La(Yg,9999,10,oe[0],0):(La(Kh,10,10,oe[1],0),Qh=Ie+lh,La(Yg,9999,10,oe[2],0)),Rh=Ie,Sh=Mf);g.beginPath();g.lineWidth=2;g.strokeStyle=Og;for(b=0;b<ma.length;b+=2)0==b?g.moveTo(ma[b]/C,ma[b+1]/m):g.lineTo(ma[b]/C,ma[b+1]/m);pe&4<ma.length&&g.lineTo(ma[0]/C,ma[1]/m);g.stroke();for(b=0;b<ma.length;b+=
2)g.beginPath(),g.rect(ma[b]/C-2,ma[b+1]/m-2,5,5),g.stroke()}if(Hb)for(b=0;b<u.length;b++){a=u[b].type;g.beginPath();g.strokeStyle=u[b].color;g.lineWidth=u[b].width;if("0"==a)a=Math.atan2(u[b].xe-u[b].x,u[b].ye-u[b].y),e=u[b].x+u[b].width*Math.sin(a),f=u[b].y+u[b].width*Math.cos(a),g.beginPath(),g.moveTo(e,f),g.lineTo(u[b].xe,u[b].ye),d=12+u[b].width/5,g.moveTo(e+d*Math.sin(a-.523599),f+d*Math.cos(a-.523599)),g.lineTo(e,f),g.lineTo(e+d*Math.sin(a+.523599),f+d*Math.cos(a+.523599));else if("1"==a)g.arc(u[b].x,
u[b].y,u[b].size,0,2*Math.PI);else if("2"==a)g.rect(u[b].x-u[b].size,u[b].y-u[b].size,2*u[b].size,2*u[b].size);else if("3"==a){g.moveTo(u[b].xp[0],u[b].yp[0]);for(e=1;e<u[b].xp.length;e++)g.lineTo(u[b].xp[e],u[b].yp[e]);g.lineTo(u[b].xp[0],u[b].yp[0])}else if("4"==a)for(g.moveTo(u[b].xp[0],u[b].yp[0]),e=1;e<u[b].xp.length;e++)g.lineTo(u[b].xp[e],u[b].yp[e]);else"5"==a&&(g.fillStyle=u[b].color,g.font=u[b].width+"pt arial",a=g.measureText(u[b].text).width,g.fillText(u[b].text,u[b].x-a/2,u[b].y+u[b].width/
2));g.stroke()}Rc&&(b=Ac*(Ke-ae)/F,a=fe*(Le-be)/E,b=" "+Math.sqrt(b*b+a*a).toFixed($f)+" "+Zf+" ",La(zh,ae/C,be/m,b,-1),g.beginPath(),g.strokeStyle=ag,g.lineWidth=3,g.moveTo(Ke/C,Le/m),g.lineTo(ae/C,be/m),g.stroke(),g.closePath());Db&&La(ug,qh,rh,sh,-1);if(Mb||ld)if(V=ra.getX(),A=V*C,Q=ra.getY(),x=Q*m,0<=A&&0<=x){oa=P+A/F;pa=O+x/E;if(ld){yb();Th=Wf+$a[0].toFixed(Se)+"  "+Xf+$a[1].toFixed(Se);b=Q;if(Rc||Db)b=Q+Yf.fontHeight+6;La(Yf,V+10,b,Th,-1)}if(Mb&&Jc&&Qc)if(oa=Math.round(oa),pa=Math.round(pa),
Ve)Ra.clearRect(0,0,1,1),Ra.drawImage(Ea[r],oa,pa,1,1,0,0,1,1),N=Ra.getImageData(0,0,1,1).data,M=0,ud(!1);else for(b=0;b<la;b++)if(a=la-b-1,L[r][a].gotit&&l[a].checked&&(a==mb||null!=mc[a]&&0<=mc[a])){Ra.clearRect(0,0,1,1);a==mb?Ra.drawImage(Xb[r],oa,pa,1,1,0,0,1,1):Ra.drawImage(L[r][a],oa,pa,1,1,0,0,1,1);N=Ra.getImageData(0,0,1,1).data;M=mc[a];null!=M&&ud(a==mb||Sg);break}}!ib||bb||kc||Mb||null==na||(g.drawImage(na.can,0,0,na.width,na.height,na.xmin/C,na.ymin/m,na.width/C,na.height/m),La(ug,(na.xmin+
na.xmax)/2/C,(na.ymin+na.ymax)/2/m,na.tip,0),Nf=!0)}function ud(b){Me=999;cc=bg;var a=rb[M].length-1;if(0==N[3])cc=re[M];else{if(cg)dc=N[0];else if(b)Pf=0,dc=N[0],Me=0;else for(var d=0;d<a;d++)ec[0]=N[0]-Ua[M][d],0>ec[0]*(Ua[M][d+1]-N[0]-1)||(ec[1]=N[1]-Va[M][d],0>ec[1]*(Va[M][d+1]-N[1]-1)||(ec[2]=N[2]-Wa[M][d],0>ec[2]*(Wa[M][d+1]-N[2]-1)||(sd=nf[M][d],Qf=ec[sd]/Nc[M][d][sd],th=Math.abs(ec[uh[sd]]-Qf*Nc[M][d][uh[sd]])+Math.abs(ec[vh[sd]]-Qf*Nc[M][d][vh[sd]]),th<Me&&(dc=d,Me=th,Pf=Qf))));if(999>Me)cc=
Lc[M][dc],-1!=Ub[M][dc]&&(wh=rb[M][dc],0!=Pf&&(wh+=Pf*(rb[M][dc+1]-rb[M][dc])),cc=cc+" "+wh.toFixed(Ub[M][dc])+" "+Kc[M][dc]);else if(b||0<xd){var c=-1;if(b)c=N[0];else for(d=0;d<a;d++)if(Math.abs(N[0]-Ua[M][d])<xd&&Math.abs(N[1]-Va[M][d])<xd&&Math.abs(N[2]-Wa[M][d])<xd){c=d;break}-1!=c&&(cc=Lc[M][c],-1!=Ub[M][c]&&(cc=cc+" "+rb[M][c].toFixed(Ub[M][c])+" "+Kc[M][c]))}}"hide"!=cc&&La(Ah,V-10,Q,cc,1)}function ea(){if(Qc)try{G.clearRect(0,0,T,X);G.globalAlpha=1;if(!Fg)if(pd&&null!=Yb&&0<=U&&Yb[U].gotit)G.drawImage(Yb[U],
P*ja[U],O*ja[U],Ya*ja[U],Xa*ja[U],0,0,T,X);else if(Ea[r].gotit&&(null!=$e?Ka(Ea[r],P,O,Ya,Xa,$e):G.drawImage(Ea[r],P,O,Ya,Xa,0,0,T,X)),null!=Ba&&(G.globalAlpha=1,Ea[r].gotit))for(var b=0;b<Ba.length;b+=4)G.drawImage(Ea[r],Ba[b],Ba[b+1],Ba[b+2],Ba[b+3],Ba[b]/C,Ba[b+1]/m,Ba[b+2]/C,Ba[b+3]/m);if(0<la){for(b=0;b<la;b++){var a=null!=Ec?Ec[b]:b;!bf[a]&&l[a].checked&&l[a].showMe&&(null!=le&&(G.globalAlpha=le[a]),pd&&0<=U&&null!=sa&&void 0!=sa[a]&&sa[a][U][r].gotit?G.drawImage(sa[a][U][r],P*ja[U],O*ja[U],
Ya*ja[U],Xa*ja[U],0,0,T,X):L[r][a].gotit&&(null==Fc||1===Fc[a]?null!=Cc&&0<=Cc[a]?Ka(L[r][a],P,O,Ya,Xa,Cc[a]):G.drawImage(L[r][a],P,O,Ya,Xa,0,0,T,X):0===Fc[a]&&G.drawImage(L[r][a],0,0,ka,ca,0,0,T,X)))}if(null!=nb)for(G.globalAlpha=1,b=0;b<la;b++)if(a=null!=Ec?Ec[b]:b,L[r][a].gotit&&(og[a]||l[a].checked)&&nb[a])for(var d=0;d<Z[a].length;d++)G.drawImage(null!=L[r][a].origImage?L[r][a].origImage:L[r][a],Z[a][d][0],Z[a][d][1],Z[a][d][2],Z[a][d][3],Z[a][d][4]/C,Z[a][d][5]/m,Z[a][d][2]/C,Z[a][d][3]/m);
Mb&&S()}Xg&&ua();if(Ff)for(G.globalAlpha=1,a=0;a<jb;a++)if(null!=kb[a]){var c=kb[a];null!=c.icon&&(c.icon.style.visibility="hidden");if((-1==c.frame||c.frame==r)&&null!=c.icon&&c.icon.gotit&&(-1==c.overlay||-1!=c.overlay&&l[c.overlay].checked)){if(c.isPan){c.zoomme&&(c.icon.style.width=Math.round(c.width*F)+"px",c.icon.style.height=Math.round(c.height*E)+"px",c.w2=Math.round(c.width*F/2),c.h2=Math.round(c.height*E/2));var e=Math.round(((c.x0-P)*F-c.w2)/C);var f=Math.round(((c.y0-O)*E-c.h2)/m);if(c.anim){if(0>=
e+c.icon.width||e>=ka||0>=f+c.icon.height||f>=ca)continue;c.icon.style.top=f+"px";c.icon.style.left=e+"px"}else G.drawImage(c.icon,c.origX,c.origY,c.width,c.height,e,f,c.width/C,c.height/m)}else G.drawImage(c.icon,c.origX,c.origY,c.width,c.height,c.x0/C,c.y0/m,c.width/C,c.height/m);c.icon.style.visibility="visible"}}}catch(k){J("Error:"+k)}}function ua(){if(gf&&Cb>Fa){G.save();G.fillStyle="blue";G.strokeStyle="white";G.lineWidth=3;G.strokeRect(te,ue,200,14);G.fillRect(te,ue,Fa/Cb*200,14);var b=G.measureText("Loading images").width;
G.fillStyle="orange";G.font="14px arial";G.fillText("Loading images",te+100-b/2,ue+11);G.restore()}else Xg=!1,Re&&(jc.style.visibility="hidden");Fa>=Cb&&!ya&&va(qa(r));void 0!=ve&&Fa>=Cb&&ve(!0)}function J(b){if(de&&Qe&&!Qe.closed)try{Qe.document.write(b+"<br>")}catch(a){}}function p(){ya&&Lb(wf);Uh=r==qa(y-1)?dg+gb:gb;ea();setTimeout(function(){$h(p)},Uh)}function ce(b){for(;-180>b;)b+=360;for(;180<b;)b-=360;return b}function Yh(){var b,a,d,c,e,f,g,h,m=Math.PI/180;this.init=function(c){for(var d=
[],n=1;n<c.length;n++)d[n]=parseFloat(c[n]);a=d[1];b=d[4]/d[5];e=d[6];f=d[7];c=this.toXY(d[2],d[3]);e=c[0];f=c[1]};this.toXY=function(n,g){d=b*ce(g-a)*m-e;c=-b*n*m-f;return[d,c]};this.toLatLon=function(c,d){g=-(d+f)/b/m;h=ce((c+e)/b/m+a);return[g,h]}}function Xh(){var b,a,d,c,e,f,g,h,m,t,r,u,v,p,w,y,z,x,A,C,l,F,D,E,B,G,I,J,L,K,M,H=Math.PI/180;this.init=function(c){for(var d=[],e=1;e<c.length;e++)d[e]=parseFloat(c[e]);b=d[1];a=d[2];C=0==d[8]?!1:!0;l=d[6];F=l*l;D=F*F;E=D*F;B=D*D;g=d[5]/d[7];M=d[7];
C?(h=Math.cos(H*b),m=Math.sin(H*b)):(h=Math.cos(-b*H),m=Math.sin(-b*H));z=h/Math.sqrt(1-F*m*m);A=(1-l*m)/(1+l*m);y=C?Math.tan(Math.PI/4-b*H/2)/Math.pow(A,l/2):Math.tan(Math.PI/4- -b*H/2)/Math.pow(A,l/2);p=d[9];w=d[10];c=this.toXY(d[3],d[4]);p=c[0];w=c[1]};this.toXY=function(n,q){C?(e=H*n,f=H*(q-a)):(e=H*-n,f=H*(a-q));A=(1-l*Math.sin(e))/(1+l*Math.sin(e));x=Math.tan(Math.PI/4-e/2)/Math.pow(A,l/2);G=90!=b&&-90!=b?g*z*x/y:2*g*M*x/Math.sqrt(Math.pow(1+l,1+l)*Math.pow(1-l,1-l));d=G*Math.sin(f);c=G*Math.cos(f);
C||(d=-d,c=-c);t=d-p;r=c-w;return[t,r]};this.toLatLon=function(f,n){d=f+p;c=n+w;G=Math.sqrt(d*d+c*c);x=90==b||-90==b?G*Math.sqrt(Math.pow(1+l,1+l)*Math.pow(1-l,1-l))/(2*g*M):G*y/(g*z);I=Math.PI/2-2*Math.atan(x);J=Math.sin(2*I);L=Math.sin(4*I);K=Math.sin(6*I);e=I+J*F/2+5*J*D/24+J*E/12+13*J*B/360+7*L*D/48+29*L*E/240+811*L*B/11520+7*K*E/120+81*K*B/1120+4279*Math.sin(8*I)*B/161280;C?(u=e/H,v=Math.atan2(d,c)/H+a):(u=-e/H,v=-Math.atan2(-d,-c)/H+a);return[u,ce(v)]}}function Zh(){var b,a,d,c,e,f,g,h,m,t,
r,l,v,p,u,w,y,x,z,C,A,F,D,B,E,G,I,H,J,L,K,M,P,O,Q,N=Math.PI/180;this.init=function(c){for(var e=[],f=1;f<c.length;f++)e[f]=parseFloat(c[f]);b=e[1];a=e[2];d=e[3];B=e[7];E=B*B;G=E*E;I=G*E;H=G*G;h=e[6]/e[8];m=Math.cos(N*b);t=Math.cos(N*a);l=Math.sin(b*N);r=Math.sin(a*N);A=m/Math.sqrt(1-E*l*l);F=t/Math.sqrt(1-E*r*r);z=Math.sqrt((1-l)/(1+l)*Math.pow((1+B*l)/(1-B*l),B));C=Math.sqrt((1-r)/(1+r)*Math.pow((1+B*r)/(1-B*r),B));K=(Math.log(A)-Math.log(F))/(Math.log(z)-Math.log(C));M=A/(K*Math.pow(z,K));O=h*M*
Math.pow(z,K);y=e[9];x=e[10];c=this.toXY(e[4],e[5]);y=c[0];x=c[1]};this.toXY=function(a,b){f=N*a;g=N*ce(b-d);Q=Math.sin(f);D=Math.sqrt((1-Q)/(1+Q)*Math.pow((1+B*Q)/(1-B*Q),B));L=h*M*Math.pow(D,K);P=K*g;c=L*Math.sin(P);e=O+L*Math.cos(P);v=c-y;p=e-x;return[v,p]};this.toLatLon=function(a,b){c=a+y;e=b+x;L=Math.abs(K)/K*Math.sqrt(c*c+(O-e)*(O-e));D=Math.pow(L/(h*M),1/K);J=Math.PI/2-2*Math.atan(D);P=0>K?Math.atan(-c/(e-O)):Math.atan(c/(O-e));g=P/K;f=J+(E/2+5/24*G+I/12+13/360*H)*Math.sin(2*J)+(7/48*G+29/
240*I+811/11520*H)*Math.sin(6*J)+(7/120*I+81/1120*H)*Math.sin(6*J)+4279/161280*H*Math.sin(8*J);u=f/N;w=ce(d-g/N);return[u,w]}}var fg,X,T,ca,ka,C,m,Pg,Qg,Eb,Fb,jc,Re,ra,de,Gf,Qe,uc,Rf,af=!1,z,D,uf,vf,Ta,sc,hd,Ab,G,Ra,lc,g,Ld,tf,y,za,la,ha,bf,Pb,Ec,Qb,ne,ba,vg,Ea,L,l,le,Pd,Db,sh,qh,rh,bd,Ad,hg,K,ig,Sf,xh,V,Q,A,x,oa,pa,Ya,Xa,P,O,Rd,fb,tc,Jh,ya,Pa,ze,r,He,wf,Yd,rc,gd=!0,je,Tf,ee,e,gb,Rb,Hc,ve,hf,dg,Uh,zd,xa,id,Dc,mb,Ma,Xb,Oc,Od,rf,we,$e,se,Md,jh,Xc,ab,Hf,If,Jf,Kf,Nh,bc,Cc,Oa,od,Ce,De,gh,ub,kh,hh,dh,eh,
fh,Bd,gg,kb,jb,Ff,ef,mf,fa,Mc,Xd,Ug,sb,Da,N,Uf,Na,xe,ib,jd,sf,Nd,na,Nf,nc,ad,ja,U,Yb,Pc,sa,Ga,pd,Za,Ha,wc,Ef,Ee,Wc,Df,Qc,$c,Bb,qb,pb,Gb,Tb,Sb,ke,Sc,tb,nd,oe,jf,pe,Og,ma,Kh,Yg,Rh,Qh,Sh,Zb,bb,Qa,Kb,vb,qd,nh,Mg,oh,ph,Ng,Bh,ob,Zd,Je,$d,yh,Jd,pf,mh,Of,rd,W,Ge,Wb,me,pg,oc,Cd,Dd,cd,qg,rg,Mh,Bf,Cf,zf,Af,Td,u,yf,bh,ac,ch,ia,Hb,Vc,Ud,Uc,Tc,Be,Lh,Wd,Vd,vc,Ib,Zg,$g,wa,wg,ed,F,E,ye,Fe,Lg,qc,Id,Kg,Jg,ta,Gc,fd,Ne,ff,jg=!1,kg,lg,mg,cf,ng,Qd,hb,Ae,Sd,qf,$b,kc,Ke,Le,$f,ge,Ie,Lf,lh,Mf,Vg=!0,Wg,ae,be,zh,ag,Ue,Aa,Te,
he,Rc,Ac,fe,Zf,ug,kd,ld,Se,Wf,Xf,Yf,Vb,$a,Th,of,Tg,Gh,Hh,Ba,Jb,ih,Fc,nb,Z,og,xf,qe,Ic,Gg,Ig,Hg,mc,Mb,md,ie,Jc,Kc,Lc,Ub,sd,Me,Ah,bg,xd,cg,Ve,df,sg,tg,dd,Oh,Ph,dc,Pf,Qf,uh,vh,ec,M,th,cc,wh,rb,w,Nc,Sg,Ua,Va,Wa,Kd,nf,re,Vh,yd,We,Bc,gf,Xe,Ye,Ze,Nb,Ob,eg,Xg,te,ue,Fa,Cb,Ed,Fg,xg,Fd,zg,Gd,Bg,yg,Ag,Eg,Cg,Hd,Dg,wd,pc,ai="N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N".split(" "),$h=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||
function(b){setTimeout(b,10)},t=function(b){return document.createElement(b)},B=function(b,a){if(null!=b)return 0==b.trim().toLowerCase().indexOf(a)},Ih=function(b,a){if(null!=b)return b=b.trim(),b.lastIndexOf(a)===b.length-1},Fh=function(b){void 0==Rf&&(Rf=t("textarea"));Rf.innerHTML=b;return Rf.value},ah=function(b,a,d){var c=t("select");c.style.width="70px";c.style.margin="5px";for(var e=0;e<b.length;e++){var f=t("option");f.innerHTML=b[e];f.value=a[e];c.add(f)}c.addEventListener("change",d,!1);
return c},Eh=function(b){b=b.split(",");ha=Array(y);for(var a=0;a<b.length;a++){var d=b[a].split("&");la=b.length;for(var c=0;c<y;c++)0===a&&(ha[c]=Array(la)),ha[c][a]=d[c].trim(),null!=pc?ha[c][a]=(pc+ha[c][a]).trim():null!=ba&&(ha[c][a]=(ba+ha[c][a]).trim())}$c=!1},Ch=function(b){b=b.split(",");y=b.length;za=Array(y);for(var a=0;a<y;a++)za[a]=null!=ba?ba+b[a].trim():b[a].trim();$c=!1;y>la&&(la=0)},Dh=function(b,a,d){var c=b;null!=ba&&(c=ba+b);za=Array(y);for(var f=0;f<y;f++){b=f*d+a;if(0<=c.indexOf("*"))za[f]=
c.replace("*",b);else if(0<=c.indexOf("?")){for(var g=c;0<=g.lastIndexOf("?");){var k=g.lastIndexOf("?");g=g.substring(0,k)+b%10+g.substring(k+1);b=Math.floor(b/10)}za[f]=g}else za[f]=c+f;J("image filename = "+za[f])}b=e.reverse_order;null!=b&&B(b,"t")&&za.reverse();$c=!1;y>la&&(la=0)};HTMLCanvasElement.prototype.toBlob||Object.defineProperty(HTMLCanvasElement.prototype,"toBlob",{value:function(b,a,d){d=window.atob(this.toDataURL(a,d).split(",")[1]);for(var c=d.length,e=new Uint8Array(c),f=0;f<c;f++)e[f]=
d.charCodeAt(f);b(new Blob([e],{type:a||"image/png"}))}});this.setup=function(b,a,d){void 0==a&&(a="MORdivcan");Wg=d;z=document.getElementById(a);wd="center";z.align=wd;Ta=t("div");Ta.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;");Ab=t("canvas");Ab.setAttribute("style","position:absolute;top:0;left:0;z-index:1;");lc=t("canvas");lc.setAttribute("style",
"position:absolute;top:0;left:0;z-index:6;");g=lc.getContext("2d");g.imageSmoothingEnabled=!1;Ld=t("canvas");Ld.setAttribute("style","position:absolute;top:0;left:0;z-index:10;");tf=Ld.getContext("2d");tf.imageSmoothingEnabled=!1;sc=t("div");sc.setAttribute("style","position:absolute;top:0;left:0;z-index:5;overflow:hidden;border-width:0px;padding:0px;margin:0px;");hd=t("div");hd.setAttribute("style","position:absolute;top:0;left:0;z-index:10;overflow:hidden;border-width:0px;padding:0px;margin:0px;");
hd.appendChild(Ld);se=t("canvas");Ta.appendChild(hd);Ta.appendChild(Ab);Ta.appendChild(lc);Ta.appendChild(sc);z.appendChild(Ta);ra=new PEvs(Ta,HAniS.down,HAniS.up,HAniS.move,HAniS.drag,null,HAniS.canTip);z.setAttribute("tabindex",0);z.addEventListener("keyup",function(a){Hb||ee||(Tf=!1,a.preventDefault(),a.stopPropagation())},!1);z.addEventListener("keypress",function(a){Hb||ee||(a.preventDefault(),a.stopPropagation())},!1);z.addEventListener("keydown",function(a){Hb||ee||(a.preventDefault(),a.stopPropagation(),
Tf=a.ctrlKey?!0:!1,37==a.keyCode?(R(!1),Lb(-1),ea()):39==a.keyCode?(R(!1),Lb(1),ea()):32==a.keyCode?HAniS.toggleIsLooping():82==a.keyCode&&a.altKey&&HAniS.resetZoom())},!1);hd.addEventListener("mouseenter",function(a){z.focus()},!1);z.style.outlineWidth="0px";z.style.outline="none";z.focus();tc=r=0;Yd=!1;wf=1;Pa=ya=!0;jb=la=y=0;je=!0;Ec=null;rc=!0;gb=500;Rb=100;Hc=2E3;hf=30;dg=0;We=6E4;Bc=null;yd=!1;ja=vg=ne=pc=ba=null;pd=!1;U=-1;fd=!1;Fe=ye=E=F=1;Ne=!1;O=P=Xa=Ya=pa=oa=x=A=Q=V=0;Lg=!1;gd=Vg=!0;Ef=
Re=af=!1;Bd=-1;Oa=[];sb=0;Ff=!1;fa=null;Mc=-1;mf=0;Xd=!1;Ha=null;ue=te=Fa=Cb=0;Sg=!1;M=0;Db=ef=Qc=!1;Ke=Le=ae=be=0;Rc=kc=!1;Aa=[];Aa.push("default");Aa.push("default");Te="default";ld=!1;he="default";Vb=null;$a=[0,0];ib=qf=ge=!1;ad=!0;na=nc=null;tb=Nf=!1;pe=!0;Ue="default";Rd=!0;ma=[];Mb=Ve=!1;ie="default";Jc=!1;uh=[1,0,0];vh=[2,2,1];ec=[];mc=[];Dc=id=bb=!1;me=Ge=0;Jb=vf=uf=D=ub=null;ih=0;Hb=ee=Tf=!1;a=t("canvas");a.height=1;a.width=1;Ra=a.getContext("2d");Ra.imageSmoothingEnabled=!1;sf=t("canvas");
de=!1;"string"===typeof b?0>b.indexOf("\n")?Vf(b):f(b.split("\n")):f(b)};this.newBasenames=function(b,a,d,c){Qc=!1;Pa=ya;R(!1);y=c;Dh(b,a,d);rc=!0;gc()};this.newFilenames=function(b){Qc=!1;Pa=ya;R(!1);Ch(b);rc=!0;gc()};this.newOverlayFilenames=function(b){Qc=!1;Pa=ya;R(!1);Eh(b);rc=!0;gc()};this.newProbeTable=function(b){Jc=!1;H(b.trim())};this.reloadFOF=function(){J("reload FoF = "+Bc);Oe("r");$c?Wh(Vh,!1):(Pa=null==ze?!0:ya,rc=!0,gc())};this.getFOF=function(){var b=e.file_of_filenames.trim();HAniS.newFOF(null!=
ne?ne+b:b,!0)};this.newFOF=function(b,a){HAniS.resetZoom();Wh(b,a)};var Wh=function(b,a){var d,c,e,f,g=new XMLHttpRequest,h,m,r,t,l,v,p,u=null,w=!1;Ug=sb;Qc=!1;Pa=ya;R(!1);a&&va(tc);sb=y=0;za=[];K=Na=null;xh=[];for(Sf=null;sc.hasChildNodes();)sc.removeChild(sc.lastChild);xe=0;pd=ib=jd=!1;sa=Pc=Yb=null;Ga=[];wc=-1;ha=[];var x=!1;if(null==ob||null!=Jd)ob=[];J("new FOF="+b);bb&&(null!=Zb&&(I(Zb,!0,"extrap on"),z.style.cursor="default",R(Pa),Qa=-1),bb=!1,S());tb&&(null!=Sc&&(I(Sc,!0,"mark on"),z.style.cursor=
"default",R(Pa),nd=-1),tb=!1,S());g.onload=function(){var a=this.responseText.split("\n");for(d=0;d<a.length;d++)if(!(2>a[d].length)&&(h=a[d].trim(),J("FOF: "+h),0!=h.indexOf("#")))if(0==h.indexOf("frame_labels"))l=h.split("="),Za=l[1].split(",");else if(0==h.indexOf("redirect"))for(l=h.split("="),p=l[1].split(","),Sf=p[0].trim(),c=1;c<p.length;c++){var b=parseInt(p[c],10)-1;xh[b]=!0}else if(0==h.indexOf("slice")){l=h.split("=");p=l[1].split(",");K=[];for(c=0;c<p.length;c++)K[c]=parseInt(p[c],10);
K[2]=K[2]-K[0]+1;K[3]=K[3]-K[1]+1;4<K.length&&(K[6]=K[6]-K[4]+1,K[7]=K[7]-K[5]+1)}else if(0==h.indexOf("fof_extension"))l=h.split("="),u=l[1].trim();else if(0==h.indexOf("probe_table"))l=h.split("="),Jc=!1,H(l[1].trim());else if(0==h.indexOf("image_base"))l=h.split("="),ba=l[1].trim();else if(0==h.indexOf("overlay_base"))l=h.split("="),pc=l[1].trim();else if(0==h.indexOf("high_res_basemap")){l=h.split("=");p=l[1].split(",");Pc=[];for(c=0;c<p.length;c++)Pc[c]=p[c].trim(),null!=ba&&(Pc[c]=ba+Pc[c]);
pd=!0}else if(0==h.indexOf("high_res_overlay"))for(l=h.split("="),v=l[1].split("&"),e=0;e<v.length;e++){p=v[e].split(",");wc=parseInt(p[0].trim(),10)-1;Ga[wc]=[];for(c=1;c<p.length;c++)Ga[wc][c-1]=p[c].trim(),Ih(Ga[wc][c-1],"/")||(null!=pc?Ga[wc][c-1]=pc+Ga[wc][c-1]:null!=ba&&(Ga[wc][c-1]=ba+Ga[wc][c-1]));pd=!0}else if(0==h.indexOf("high_res_zoom")){l=h.split("=");p=l[1].split(",");ja=[];for(c=0;c<p.length;c++)ja[c]=parseFloat(p[c].trim());Ja()}else if(0==h.indexOf("hoverzone"))Pe(h);else if(0==h.indexOf("hotzone"))cb(h);
else if(0==h.indexOf("hotspot"))w||(kb=null,jb=0,w=!0),Yc(h);else if(0==h.indexOf("toggle_onoff"))l=h.split("="),Ee=l[1].split(",");else if(0==h.indexOf("coordinates"))l=h.split("="),wb(l[1]);else if(0==h.indexOf("map_scale"))l=h.split("="),p=l[1].split(","),Ac=parseFloat(p[0]),fe=1<p.length?parseFloat(p[1]):Ac;else if(0==h.indexOf("times")){l=h.split("=");p=l[1].split(",");for(d=0;d<p.length;d++)ob[d]=parseInt(p[d].trim(),10);x=!0}else{null!=Jd&&(b=h.match(Jd),null!=b&&2==b.length?(ob.push(parseInt(b[1],
10)),J("+ + + Extrap time = "+b[1]),x=!0):J("+ + + Cannot parse times using "+Jd+" from line: "+h));e=h.indexOf(" ");0>e&&(e=h.length);za[y]=h.substring(0,e).trim();null!=ba&&(za[y]=ba+za[y]);h=h.substring(e+1);b=h.indexOf('"');0<=b&&(null==Za&&(Za=[]),e=h.substring(b+1),b=e.indexOf('"'),0<=b&&(Za[y]=e.substring(0,b),0==y&&(Ha.innerHTML=Za[0])));ha[y]=[];b=h.indexOf("overlay");if(0<=b)for(m=h.substring(b),b=m.indexOf("="),0>b&&J("Cannot find a = sign in "+m),r=m.substring(b+1),m=r.trim(),r=m.split(","),
la=r.length,J("numOverlays set to "+la),f=0;f<r.length;f++)ha[y][f]=r[f].trim(),null!=Sf&&xh[f]?ha[y][f]=(Sf+ha[y][f]).trim():null!=pc?ha[y][f]=(pc+ha[y][f]).trim():null!=ba&&(ha[y][f]=(ba+ha[y][f]).trim());y+=1}x&&Ia(ob);null!=u?(a=new XMLHttpRequest,a.onload=function(){var a=this.responseText.split("\n");for(d=0;d<a.length;d++)2>a[d].length||(t=a[d].trim(),J("ext_FOF: "+t),0!=t.indexOf("#")&&(0==t.indexOf("hotzone")?cb(t):0==t.indexOf("hotspot")&&Yc(t)));Sa()},a.onerror=function(){Sa()},a.open("get",
u+"?"+Math.round(1E5*Math.random()),!0),a.send()):Sa()};Vh=b;g.open("get",b+"?"+Math.round(1E5*Math.random()),!0);g.send()};this.setWindowSize=function(b,a){if(null!=z){z.style.height=a+"px";z.style.width=b+"px";z.style.padding="0px";a=a-(null!=uf?uf.offsetHeight:0)-(null!=vf?vf.offsetHeight:0)-(null!=ub?ub.offsetHeight:0)-ih*(null!=Jb?Jb.offsetHeight:0);a>ca&&(a=ca);var d=a*ka/ca;d>b&&(d=b,a=b*ca/ka);a=Math.floor(a);d=Math.floor(d);gd||(td(d,a),S())}};this.drag=function(b){tb||(V=ra.getX(),Q=ra.getY(),
Hb?(b=u.length-1,u[b].xe=V,u[b].ye=Q,u[b].xp.push(V),u[b].yp.push(Q),u[b].size=Math.round(Math.sqrt(Math.pow(V-u[b].x,2)+Math.pow(Q-u[b].y,2)))):(A=V*C,x=Q*m,Rc=Db=!1,kc&&(!ge||ge&&b.shiftKey)?(ae=A,be=x,Rc=!0):(ta&&E!=Fe?(P=oa-A/F,O=pa-x/E,db(),oa=Math.round(P+A/F),pa=Math.round(O+x/E)):tb||bb||!ib||(na=null,ad&&0<=A&&0<=x&&(N=Nd.getImageData(A,x,1,1).data,0!=N[3]&&(na=Na[N[3]-1]))),Ne=!0,ea())),S())};this.resetZoom=function(){F=ye;E=Fe;U=-1;null!=wa&&(I(wa,!0,"zoom on"),ta=!1);oa=A;pa=x;O=P=0;Xa=
ca;Ya=ka;Ja();ea();jd&&(ib=!0)};this.canTip=function(){var b;Db=!1;V=ra.getX();A=V*C;Q=ra.getY();x=Q*m;if(!((tb||bb)&&x<ph&&x>oh&&A>nh)){oa=Math.round(P+A/F);pa=Math.round(O+x/E);if(0!=sb)for(b=0;b<sb;b++)if(Da[b].overlay>=la)J(" Error...hotzone overlay # "+Da[b].overlay+" > number of overlays = "+la);else if(l[Da[b].overlay].checked&&(Ra.clearRect(0,0,1,1),Ra.drawImage(L[r][Da[b].overlay],oa,pa,1,1,0,0,1,1),N=Ra.getImageData(0,0,1,1).data,Uf=(N[0]<<16)+(N[1]<<8)+N[2],Uf==Da[b].color)){Db=!0;qh=V;
rh=Q;sh=Da[b].tip;break}if(0!=jb)for(b=jb-1;0<=b;b--)if(null!=kb[b]){var a=kb[b];if(-1==a.frame||a.frame==r)if(-1==a.overlay||l[a.overlay].checked){var d=!1;if(a.isPan)if(a.isIcon){var c=(a.x0-P)*F-a.w2;var e=(a.y0-O)*E-a.h2;A>c&&A<c+a.width&&x>e&&x<e+a.height&&(d=!0)}else c=(a.x0-P)*F,e=(a.y0-O)*E,A>c&&A<c+a.width*F&&x>e&&x<e+a.height*E&&(d=!0);else A>a.x0&&A<a.x1&&x>a.y0&&x<a.y1&&(d=!0);if(d&&null!=a.tip){Db=!0;qh=V;rh=Q;sh=kb[b].tip;break}}}S()}};this.move=function(){if(!bb&&ib&&(na=null,ad)){var b=
ra.getX()*C,a=ra.getY()*m;0<=b&&0<=a&&(N=Nd.getImageData(b,a,1,1).data,0!=N[3]&&(na=Na[N[3]-1]))}bb&&2<=Qa&&(V=ra.getX(),A=V*C,Q=ra.getY(),x=Q*m);S()};this.down=function(){Db&&(Db=!1,S());V=ra.getX();A=V*C;Q=ra.getY();x=Q*m;Ke=A;Le=x;ae=Ke;be=Le;oa=Math.round(P+A/F);pa=Math.round(O+x/E);Ne=!1;if(Hb){var b={};b.x=V;b.y=Q;b.xe=V;b.ye=Q;b.xp=[V];b.yp=[Q];b.type=Wd.value;b.color=Vd.value;b.width=vc.value;b.text=Ib.value;b.size=0;u.push(b)}};this.up=function(b){Db=!1;if(!Hb){if(bb||tb){V=ra.getX();A=V*
C;Q=ra.getY();x=Q*m;if(tb){nd=1;if(0<nd&&x/m<Sh){if(A/C>Rh){ma.pop();ma.pop();0==ma.length&&(nd=0);S();return}if(A/C<Qh){S();b=window.open("","Mark Points");b.document.write("<div>Marked Points<br>");for(var a=[],d=0;d<ma.length;d+=2)oa=P+ma[d]/F,pa=O+ma[d+1]/E,yb(),b.document.write($a[0].toFixed(4)+","+$a[1].toFixed(4)+"<br>"),0==d&&(a[0]=$a[0],a[1]=$a[1]);pe&&b.document.write(a[0].toFixed(4)+","+a[1].toFixed(4)+"<br>");return}}ma.push(A);ma.push(x);S();return}if(3>Qa)if(Kb[Qa]=A,vb[Qa]=x,qd[Qa]=
pf[r],0==Qa)Qa=1,va(qa(y-1)),Ge=1,dd=null;else{yh=qd[1]-qd[0];Je=(Kb[1]-Kb[0])/yh;$d=(vb[1]-vb[0])/yh;if(null!=df&&null!=Ac){d=Je*Ac;var c=$d*fe;a=Math.round(60*Math.sqrt(d*d+c*c));d=Math.atan2(d,-c)/.0174533;0>d&&(d+=360);dd=sg+ai[Math.round(d/22.5)]+" at "+a+" "+tg;Oh=Kb[0];Ph=0<$d?vb[0]-15:vb[0]+30}a=parseInt(Dd,10);W=Math.round(Math.abs(4*(a+4)/Je));rd=Math.round(Math.abs(2*(a+4)/$d));rd<W&&(W=rd);120<W?W=120*Math.floor(W/120)+60:90<W?W=120:60<W?W=90:30<W?W=60:15<W?W=30:10<W?W=15:5<W?W=10:2<W?
W=5:0==W&&(W=1);rd=qd[1]/W*W+W;Zd=1;rg&&(Zd=-1);mh=Je*W;Of=$d*W;va(qa(y-1));Qa=3;Ge=2}else if(x/m<ph&&x/m>oh&&A/C>nh&&3==Qa){ic();S();return}S()}if(Rc)Rc=!1,S();else if(null!=$b&&ta&&(kc=!1,I($b,!0,"distance on")),Ne)Ne=!1;else if(b.altKey)HAniS.resetZoom();else if(ib&&null!=na&&Nf)lb(na,"z");else{V=ra.getX();A=V*C;Q=ra.getY();x=Q*m;if(0!=sb)for(a=0;a<sb;a++)if(Da[a].overlay>=la)J(" Error...hotzone overlay # "+Da[a].overlay+" > number of overlays = "+la);else if(l[Da[a].overlay].checked&&(Ra.clearRect(0,
0,1,1),Ra.drawImage(L[r][Da[a].overlay],Math.floor(oa),Math.floor(pa),1,1,0,0,1,1),N=Ra.getImageData(0,0,1,1).data,Uf=(N[0]<<16)+(N[1]<<8)+N[2],Uf==Da[a].color)){lb(Da[a],"z");return}if(0!=jb)for(a=jb-1;0<=a;a--)if(null!=kb[a]){var e=kb[a];if(!(-1!=e.frame&&e.frame!=r||e.fromfile||-1!=e.overlay&&!l[e.overlay].checked)){var f=!1;e.isPan?e.isIcon?(d=(e.x0-P)*F-e.w2,c=(e.y0-O)*E-e.h2,A>d&&A<d+e.width&&x>c&&x<c+e.height&&(f=!0)):(d=(e.x0-P)*F,c=(e.y0-O)*E,A>d&&A<d+e.width*F&&x>c&&x<c+e.height*E&&(f=!0)):
A>e.x0&&A<e.x1&&x>e.y0&&x<e.y1&&(f=!0);if(f){lb(kb[a],"s");return}}}ta&&(ib=!1,hc(b.ctrlKey||Tf||b.which&&3==b.which||b.button&&2==b.button));ea();S()}}};this.wheel=function(b){ta&&(V=ra.getX(),A=V*C,Q=ra.getY(),x=Q*m,oa=Math.round(P+A/F),pa=Math.round(O+x/E),hc(-1==b))};this.toggleAutoRefresh=function(){yd?(I(Ic,!1,"autorefresh off"),null!=Bc&&clearInterval(Bc),yd=!1):(I(Ic,!0,"autorefresh on"),Bc=setInterval("HAniS.reloadFOF();",We),yd=!0)};this.toggleLoopRock=function(){Yd?(I(Qd,!0,"looprock rock"),
Yd=!1):(I(Qd,!1,"looprock loop"),Yd=!0)};this.toggleExtrap=function(){bb?(null!=Zb&&(I(Zb,!0,"extrap on"),z.style.cursor=Aa.pop(),null!=Bb&&(Bb.disabled=!1),R(Pa),ta=Jg,Qa=-1),bb=!1,S()):(null!=Zb&&(bb=!0,dd=null,Aa.push(z.style.cursor),z.style.cursor="crosshair",I(Zb,!1,"extrap off"),Pa=ya,null!=Bb&&(Bb.disabled=!0),ya=!1,Jg=ta,ta=!1,HAniS.resetZoom(),ic(),S()),ea())};this.doEnhance=function(b){if(id||Dc){var a=Ma[0].height,d=Ma[0].width;b=parseInt(xa.value,10);0<=b?(Hf=Ua[b],If=Va[b],Jf=Wa[b],Kf=
Kd[b],mc[mb]=b):mc[mb]=null;var c=a*d*4;for(d=0;d<Xb.length;d++)if(Ma[d].gotit){Ma[d].gotit=!1;var e=we[d].data;var f=rf[d];if(0>b)for(a=0;a<c;a+=4)e[a]=f[a],e[a+1]=f[a+1],e[a+2]=f[a+2],e[a+3]=f[a+3];else for(a=0;a<c;a+=4)ab=f[a],ab===f[a+1]&&ab===f[a+2]&&(e[a]=Hf[ab],e[a+1]=If[ab],e[a+2]=Jf[ab],e[a+3]=Kf[ab]);Oc[d].putImageData(we[d],0,0);Ma[d].gotit=!0}}};this.overClick=function(b){var a;if(b.target.checked)for(a=0;a<l.length;a++)b.target!=l[a]&&0!=b.target.name&&b.target.name==l[a].name&&(l[a].checked=
!1);ad=!0;for(a=0;a<Qb.length;a++)b.target!=l[a]&&xc(a),null!=nc&&!nc[a]&&l[a].checked&&(ad=!1),null!=xa&&a===mb&&(xa.disabled=!l[a].checked);ea()};this.toggleIsLooping=function(){ya?(ya=!1,I(Bb,!0,"startstop start")):(ya=!0,I(Bb,!1,"startstop stop"))};this.toggleZooming=function(){ta?(HAniS.resetZoom(),I(wa,!0,"zoom on")):(I(wa,!1,"zoom off"),ta=!0,null!=$b&&(kc=!1,I($b,!0,"distance on")),jd&&(ib=!0),bb&&HAniS.toggleExtrap())};this.togclick=function(b){var a=hh.getX();hh.getY();for(var d=kh,c=0;c<
Oa.length;c++){if(a>d&&a<d+od){if(b.shiftKey){0<=Oa[c]&&(R(!1),va(c));break}b=0;0<=Oa[c]&&(b=-1);eb(c,b);break}d=d+od+De}};this.doneLoading=function(b){ve=b};this.frameChanged=function(b){He=b};this.getFrame=function(){return r};this.showFrame=function(b){va(qa(b))}};
